### ISSUE TITLE
Add features matrix

### ISSUE THREAD

**Issue by behlendorf** [openzfs/openzfs-docs#10]
The OpenZFS features matrix at https://zgrep.org/zfs.html is very nice and a version of it would be good to have in the documentation.

**Comment by rlaager** [comment]
This is currently manually copied to the OpenZFS wiki: https://www.openzfs.org/wiki/Feature_Flags

**Comment by ghfields** [comment]
The matrix is also available on a site we have a bit more ownership over: http://build.zfsonlinux.org/zfs-features.html

It may be worth re-evaluating which systems are in this matrix.  Years past, I modified the .py locally to include different ones.  Perhaps it could be useful to have the .py source in openzfs-docs repo so it can be community maintained?

**Comment by gmelikov** [comment]
I may work on it after man pages. I want:
- create `scripts` folder to place generators
- store it there, clean up some bits, rework output to prepare for sphinx
- import it in our documentation hierarhy

**Comment by gmelikov** [comment]
One more note:
- [  ] add a link to each feature flag description in man page https://openzfs.github.io/openzfs-docs/man/5/zpool-features.5.html

**Comment by gmelikov** [comment]
Initial version is ready https://github.com/openzfs/openzfs-docs/pull/63

**Comment by gmelikov** [comment]
> OpenZFS 2.0 code on FreeBSD doesn't support edonr. openzfs/zfs#9664 openzfs/zfs#9901 I don't know if there is a plan to fix it. That would make the current table a half-truth since it combines Linux and Freebsd. Not sure if/how you would like to address this.

I'll try to rework it for this case later.

**Comment by rlaager** [comment]
This was merged some time ago. I broke out the couple remaining items into separate issues.
