### ISSUE TITLE
Debian Buster Root on ZFS: zed requires /run/lock to populate zfs-list.cache files (which does not exist when mounting /run as tmpfs)

### ISSUE THREAD

**Issue by aschaap** [openzfs/openzfs-docs#100]
While following the Root on ZFS guide for Debian Buster, I was unable to have `zed` populate the `/etc/zfs/zfs-list.cache/{rpool,bpool}` files until I ran `mkdir /run/lock`. 

It seems the fix referenced in https://github.com/openzfs/openzfs-docs/issues/97#issuecomment-752854190 caused this issue (originally reported in https://github.com/openzfs/zfs/issues/9945) to resurface.

@rlaager, would you add `mkdir /mnt/run/lock` to the steps preceding `chroot`, or is there a better solution?

**Comment by rlaager** [comment]
> @rlaager, would you add mkdir /mnt/run/lock to the steps preceding chroot, or is there a better solution?

Honestly, I haven't investigated this a ton, nor the original issue. But yeah, that seems good to me, so I made that change. Hopefully this doesn't create any other issues!

Thanks for the suggestion!
