### ISSUE TITLE
Ubuntu 20.04 Troubleshooting section should include commands for mounting encrypted rpool

### ISSUE THREAD

**Issue by randomphrase** [openzfs/openzfs-docs#11]
I am a bit of a beginner with ZFS, so apologies for any incorrect terminology.

If you have followed the process for installing an encrypted rpool at installation time by modifying the installer as described in the overview section, you subsequently need to use `zfs load-key rpool` (or something similar) before mounting it. The troubleshooting section should include the correct command, whatever it is.

**Comment by ghfields** [comment]
Just want to be clear... this isn't a problem with using a modified installer.  Anyone trying to use the troubleshooting section who has native encryption on their rpool will face this issue.

Submitted https://github.com/openzfs/openzfs-docs/pull/16

**Comment by rlaager** [comment]
I fixed this in d1b3973b92af1ea2105d42f1786231a82a38e179 but apparently my syntax for closing the issue was wrong. (I think it needed the # on the issue number.)
