### ISSUE TITLE
Debian ZFS on Root ZED Issues

### ISSUE THREAD

**Issue by spontaneous-emission** [openzfs/openzfs-docs#110]
@rlaager 

When following the instructions on the wiki to install ZFS on root on Debian Buster, I get hung up at step 5.7, "Fix filesystem mount ordering". `/etc/zfs/zfs-list.cache/bpool` and `/etc/zfs/zfs-list.cache/rpool` are always empty for me, even after running `zfs set canmount=on     bpool/BOOT/debian` or `zfs set canmount=noauto rpool/ROOT/debian` as suggested.

I tried running `history_event-zfs-list-cacher.sh` directly, but then this complains about a missing `/zed-functions.sh` even though it is in the same directory.

Do you have any other debugging tips to try to resolve this issue?

This is a Debian Buster 10.7 live install USB with ZFS Event Daemon 0.8.6-1~bpo10+1. I decided to use EFI boot rather than MBR.

**Comment by rlaager** [comment]
In general, I've seen zed take a few seconds. Sometimes I have to try a couple of times. Some ideas... Are you sure that zed is running (and e.g. not stopped in the background in your shell)? Are you sure that there is not a second zed running? Maybe try creating another dataset and, if that doesn't work, toggling it's canmount?

**Comment by spontaneous-emission** [comment]
It is a bit weird in that there seem to be different `zed`s running. When I run `zed -vF &`, I get
```
ZFS Event Daemon 0.8.6-1~bpo10+1 (PID 14120)
```
But then if I look at another terminal running `htop` on the target machine, I see no PID 14120 `zed`, but two running `zed` processes, with PID 14122 and 14123. When I run `fg` to bring `zed` back to the foreground and hit `Ctrl-C` to kill `zed`, both of these processes disappear.

With `zed` in verbose mode, if I run `zfs set canmount=on bpool/BOOT/debian`, I get
```
Invoking "all-syslog.sh" eid=103 pid=14125
root@debian:/# Finished "all-syslog.sh" eid=103 pid=14125 exit=0
Invoking "history_event-zfs-list-cacher.sh" eid=103 pid=14181
Finished "history_event-zfs-list-cacher.sh" eid=103 pid=14181 exit=0
```
and something similar for `zfs set canmount=auto rpool/ROOT/debian`. This all sounds good like it is not running into any errors and is calling the correct scripts.

Creating another dataset and toggling its canmount also did not make a difference.

**Comment by rlaager** [comment]
If you put a `set -x` in `/etc/zfs/zed.d/history_event-zfs-list-cacher.sh` (and run `zed` verbosely), do you get output from each command it runs? Does that shed any light on what's happening?

**Comment by theotherplanb** [comment]
I found this failing for me because /run/lock did not exist, causing zed_lock() in zed-functions.sh to fail at line 129 (eval "exec ${fd}> '${lockfile}'"). I worked around it by "mkdir /run/lock" which you can do while zed is running, and then just re-trigger the events.

(This happened consistently over several installs on two different machines.)

Great work on this, btw - thank you!!!

**Comment by fracai** [comment]
Thank you @theotherplanb 
I just ran in to this and creating the `/run/lock` directory got me past this step.

**Comment by theotherplanb** [comment]
Thanks @fracai, I'm glad it helped you.

@rlaager I guess I should mention you to make sure you see this.

**Comment by rlaager** [comment]
This `/run` thing is the gift that keeps on giving. Thanks for chasing this down!

**Comment by heapxor** [comment]
the file is missing in package, why?
https://packages.debian.org/buster/armhf/zfs-zed/filelist

**Comment by rlaager** [comment]
@heapxor If you’re asking about the cache zedlet, I think the version of ZFS in buster predates that script / the generator. Use ZFS from buster-backports (or move to bullseye, which is currently testing but will be released soon).

**Comment by heapxor** [comment]
@rlaager i dont undertand; 
i am using 
zfsutils-linux/buster-backports,buster,now 2.0.3-1~bpo10+1 armhf [installed]
  command-line tools to manage OpenZFS filesystems
zfs-zed/stable,now 0.7.12-2+deb10u2 armhf [installed]
  OpenZFS Event Daemon


and the file is not there.

**Comment by heapxor** [comment]
The point 7) is talking about that missing file; that link should provide howto on Buster ... so i am wondering whereis the Bug; in package; in howto etc.... 

https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html

**Comment by rlaager** [comment]
@heapxor If you need to discuss this further, please open a new issue. You have zfs-zed 0.7.12-2+deb10u2 installed from buster, not zfs-zed 2.x from buster-backports.
