### ISSUE TITLE
Debian/Ubuntu Root on ZFS: /root world-readable

### ISSUE THREAD

**Issue by zxyrepf** [openzfs/openzfs-docs#115]
The `/root` dataset is created with default world-readable permissions (755). Debootstrap would create `/root` with 700 permissions, but it does not change the permissions if it already exists. So I think a `chmod 700 /mnt/root` should be added to the guides.

Thank you!

@rlaager

**Comment by rlaager** [comment]
Good catch! Thanks!

**Comment by rlaager** [comment]
@didrocks I'm not sure if this happens in the installer either. I haven't tested, but just wanted to draw your attention to this.

**Comment by didrocks** [comment]
@rlaager thanks for reaching out. We also have 755 as a default for our ext4 default ubuntu installation on /. This has been validated by our security team, so I wouldn’t really diverge from our default policy.

I guess both permissions are debatable :)

**Comment by rlaager** [comment]
@didrocks Not /, /root (root’s home directory).

**Comment by didrocks** [comment]
@rlaager Ah, ok, I was thinking about /root before pivot_root is called :)

Ok, our /root is already with the correct permissions, I didn’t remember we have diverged from the Wiki, but thanks for double checking!
