### ISSUE TITLE
url fragments don't work after whatever you did to change the documentation urls

### ISSUE THREAD

**Issue by mailinglists35** [openzfs/openzfs-docs#13]
this url which was scrolling to "zfs_arc_dnode_limit" paragraph in the wiki https://github.com/zfsonlinux/zfs/wiki/ZFS-on-Linux-Module-Parameters#zfs_arc_dnode_limit_percent now shows me a message that the url has changed then when I click the new url it takes me to the start of the new page, without scrolling to the parameter.

I expect that when something change inside, that change should not reflect in user-facing area (ie. an url changes but the content and behaviour should remain the same - scroll me to [url fragment](https://en.wikipedia.org/wiki/Fragment_identifier) "#zfs_arc_dnode_limit_percent" parameter)

**Comment by gmelikov** [comment]
Unfortunately, github wiki's functionality is very limited, I didn't find any other way for redirects.

If you know better way to redirect and to make this issue topic in real life - it would be great!

One point of a new way for our documentation is to move from functionally limited github wiki, now we can do what you want here with self-generated HTML docs.

**Comment by gmelikov** [comment]
To be more precise - anchors work on new page https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/ZFS%20on%20Linux%20Module%20Parameters.html#zfs-arc-dnode-limit-percent , but github wiki can't redirect them.
