### ISSUE TITLE
"cryptsetup: ERROR: Couldn't resolve device" when following "Ubuntu 20.04 Root on ZFS" guide.

### ISSUE THREAD

**Issue by lukasz-zaroda** [openzfs/openzfs-docs#134]
I tried to follow: "[Ubuntu 20.04 Root on ZFS](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html)" guide, but on this step:

`apt install --yes grub-pc linux-image-generic zfs-initramfs zsys`

I'm getting an error:

```
update-initramfs: Generating /boot/initrd.img-5.4.0-66-generic
cryptsetup: ERROR: Couldn't resolve device rpool/ROOT/ubuntu_z9g2gb
cryptsetup: WARNING: Couldn't determine root device
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
```

I chose options for natively encrypted and mirrored setup.

**Comment by rlaager** [comment]
Is this causing any particular problem?

I should probably bring the existing note up to that step and maybe mention that this ERROR can occur (the existing note talks about the WARNING).

**Comment by lukasz-zaroda** [comment]
@rlaager It doesn't seem to cause any problem, but I think it make more sense to mention it in the guide next to, or even instead of the warning, because ERROR seems more important, and not mentioned, feels like there is going on something that is not suppose to.

**Comment by rlaager** [comment]
Agreed, and fixed.
