### ISSUE TITLE
Artix Linux Root on ZFS

### ISSUE THREAD

**Issue by rharmonson** [openzfs/openzfs-docs#143]
Where did the Artix Linux Root on ZFS go? It was found under the Arch Linux Getting Started but *poof* it's gone.

**Comment by ne9z** [comment]
I dropped the support in [this pull request](https://github.com/openzfs/openzfs-docs/pull/135) as I don't really have time to test it.

Last version is available [here](https://github.com/openzfs/openzfs-docs/blob/91d28894a74a19f1a528227925ceb5ff45dc236a/docs/Getting%20Started/Arch%20Linux/Artix%20Linux%20Root%20on%20ZFS.rst) and you are more than welcome to update the guide and add the support back.
