### ISSUE TITLE
Ubuntu Root on ZFS: '/boot/grub' on bpool for all installation

### ISSUE THREAD

**Issue by ne9z** [openzfs/openzfs-docs#147]
@rlaager

While I understand that a GRUB-writable `/boot/grub` is used for showing menu on boot failure, this advantage is dwarfed by the slow speed of zsys menu generation.

As I understands it, in order to add boot environment menu entries, zsys needs to scan initrd & ucode in the newly created boot environments. This is not necessary and time consuming. Older versions of bieaz, a BE manager developed by myself, also does this.

If `/boot/grub` is inside the same dataset as `/boot` and cloned as part of the system state, to add a boot environment entry is as simple as:

- adding `configfile ($root)/BOOT/ubuntu-newUUID@/grub/grub.cfg` to `/BOOT/ubuntu-currentUUID@/grub/grub.cfg`
- replace all occurrences of `ubuntu-currentUUID` with `ubuntu-newUUID` in `/BOOT/ubuntu-newUUID@/grub/grub.cfg`

No initrd/ucode detection needed. Thanks to this, bieaz is able to generate more than 300 menu entries under one second.
A sample menu file is the following:
```
echo 'Loading boot environment menu'
submenu 'Fri Mar 19 15:01 2021 post_-S_--noconfirm_vim' {
configfile ($root)/sys/BOOT/pac-eashcq@/grub/grub.cfg
}
submenu 'Fri Mar 19 15:01 2021 pre__-S_--noconfirm_vim' {
configfile ($root)/sys/BOOT/pac-tqgmly@/grub/grub.cfg
}
```

**Comment by rlaager** [comment]
I agree that zsys is slow, but that's a discussion for elsewhere (like the zsys project). As long as Ubuntu has installer ZFS support using zsys, that's what I'm going to match.

**Comment by ne9z** [comment]
OK, I'll open an issue there.
