### ISSUE TITLE
ZFS HOWTO - grub issue on post configuration maintenance

### ISSUE THREAD

**Issue by cosamit** [openzfs/openzfs-docs#151]
@rlaager, I have the following issue with the Debian Buster Root on ZFS HOWTO:

Hi - enroute to a Proxmox installation (on multipath sas config), I followed the Debian Buster Root on ZFS HOWTO (mirror on two devices).

I booted the live Buster CD with "install disk-detect/multipath/enable=true"

Everything was fine, I rebooted, added normal local users after reboot. I then proceeded to the "https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster" procedures.

All was well until I ran "apt update && apt full-upgrade"

Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Get:5 http://download.proxmox.com/debian/pve buster InRelease [3,051 B]
Get:6 http://download.proxmox.com/debian/pve buster/pve-no-subscription amd64 Packages [375 kB]
Fetched 477 kB in 1s (360 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  distro-info-data dkms libnvpair3linux libuutil3linux libzfs4linux libzpool4linux lsb-release python3-distutils
  python3-lib2to3 sudo zfs-dkms
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  grub-efi-amd64-signed zfs-initramfs zfs-zed zfsutils-linux
The following packages will be upgraded:
  dmsetup grub-common grub-efi-amd64 grub-efi-amd64-bin grub2-common ifupdown libdevmapper1.02.1 libnvpair3linux
  libssl1.1 libuutil3linux libzfs4linux libzpool4linux
12 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
Need to get 7,095 kB of archives.
After this operation, 8,886 kB disk space will be freed.
Do you want to continue? [Y/n] y
...
...
...
Setting up dmsetup (2:1.02.155-pve4) ...
update-initramfs: deferring update (trigger activated)
Setting up grub-common (2.02+dfsg1-18-pve1) ...
Setting up grub-efi-amd64-bin (2.02+dfsg1-18-pve1) ...
Setting up grub2-common (2.02+dfsg1-18-pve1) ...
Setting up grub-efi-amd64 (2.02+dfsg1-18-pve1) ...
Installing for x86_64-efi platform.
grub-install: error: failed to get canonical path of `bpool/BOOT/debian'.
Failed: grub-install --target=x86_64-efi
WARNING: Bootloader is not properly installed, system may not be bootable
/usr/sbin/grub-probe: error: failed to get canonical path of `rpool/ROOT/debian'.
dpkg: error processing package grub-efi-amd64 (--configure):
 installed grub-efi-amd64 package post-installation script subprocess returned error exit status 1
Processing triggers for initramfs-tools (0.133+deb10u1) ...
update-initramfs: Generating /boot/initrd.img-4.19.0-16-amd64
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for systemd (241-7~deb10u7) ...
Processing triggers for shim-signed:amd64 (1.33+15+1533136590.3beb971-7) ...
Errors were encountered while processing:
 grub-efi-amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)

Of course, this left my system unbootable. At next boot attempt the rpool was missing.

Can you tell me, once a system is configured using this guide, what is the proper way to process updates such that you don't get pinched?

Thanks,
Phil

**Comment by rlaager** [comment]
It sounds like this was a newly installed system, so you can just start over? On a real system, you shouldn't be saying "yes" to removing ZFS or rebooting after the system tells you the bootloader is broken.

This is the list of packages removed:
grub-efi-amd64-signed zfs-initramfs zfs-zed zfsutils-linux

You'll need to figure out why it is trying to remove those. There are any number of ways, but if I'm being honest, I'd do it in a rather "dumb" way. I'd probably do this:

```
apt update
apt dist-upgrade --dry-run --yes
# Here, you're just confirming what it would want to do.
# Previously, it wanted to upgrade thes:
# dmsetup grub-common grub-efi-amd64 grub-efi-amd64-bin grub2-common
# ifupdown libdevmapper1.02.1 libnvpair3linux libssl1.1 libuutil3linux
# libzfs4linux libzpool4linux


# I'd probably get a the unrelated things out of the way:
apt install --dry-run --yes dmsetup ifupdown libdevmapper1.02.1 libssl1.1
# Assuming the results of that look sane, run it without --dry-run.

# Then I'd tackle the ZFS piece:
apt install --dry-run --yes libnvpair3linux libuutil3linux libzfs4linux \
    libzpool4linux
# That's probably going to tell you it wants to remove:
# zfs-initramfs zfs-zed zfsutils-linux
# Tell it you're not okay with that:
apt install --dry-run --yes libnvpair3linux libuutil3linux libzfs4linux \
    libzpool4linux zfs-initramfs zfs-zed zfsutils-linux
```

That will likely fail, saying it can't handle that combination. Figure out why. Is Proxmox shipping ZFS packages, so you're ending up with an incompatibility between Proxmox and backports?

Try looking at the output from `apt-cache policy zfsutils-linux` to see if that sheds any light on it.

**Comment by gmelikov** [comment]
Looks like a conflict between proxmox ZFS integration and Debian one.

Easiest way to install proxmox inside chroot and just don't install ZFS from debian packages.

I'll close this issue as a corner case, and it's pretty stale already too.
