### ISSUE TITLE
system not booting after applying 2020-12-05 boot/grub fix

### ISSUE THREAD

**Issue by jknockaert** [openzfs/openzfs-docs#156]
I set up a Ubuntu 20.04 Root on ZFS system with a mirror topology. I followed the guide as it was in August 2020, so with the 2020-05-30 errata fix for boot/grub. Now I read that I should revert the dataset name; so I ran the four commands as specified (properly substituting the UUID in the zfs rename command). After doing so the system will no longer boot; instead I get a grub command line...

**Comment by rlaager** [comment]
Yikes! I'm sorry that happened. I'm not able to help right now (beyond this message), but I would suggest you boot into the rescue environment, make sure everything is mounting correctly, and reinstall grub and re-run update-grub. That's generic advice for a GRUB issue, not tailored to your situation.

**Comment by jknockaert** [comment]
Well, I'm not really in a hurry to solve this issue. But it's either booting into the rescue environment, or using the grub command line interface to fix it. I'm not really experienced in either, but I will try to sort it out.
I guess `update-grub` was missing from the commands I had to run to revert the dataset name?

**Comment by jknockaert** [comment]
Can't get into the rescue environment either. Perhaps I can boot from a livecd and then import the bpool to revert the dataset rename.

**Comment by jknockaert** [comment]
OK, I got that server booting again. I post the grub commands here in order for anyone running into the issue to get going again. I will later post a fix to avoid the issue.
```
set prefix=($root)/boot/grub@
normal
```

**Comment by jknockaert** [comment]
To further update: `update-grub` doesn't solve the issue. The problem is that the grub prefix variable is not set correct in `/boot/efi/EFI/ubuntu/grub.cfg`. I am not sure about the correct mechanism to update that file (perhaps manually?). There may be a link with issue #118.

**Comment by jknockaert** [comment]
This issue went after the most recent grub update that came from the the official ubuntu repositories (not sure whether it was the backport or security repo).

**Comment by rlaager** [comment]
Good deal! Sorry I wasn't of more help. I guess I'll close this.

**Comment by jknockaert** [comment]
After verifying I observed that the issue is solved only partially. The prefix variable is now set correctly in `/boot/efi/EFI/ubuntu/grub.cfg` and as a result the booting issues are gone. But the mechanism that fixed this issue left the mirrored `/boot/efi2/EFI/ubuntu/grub.cfg` untouched...
