### ISSUE TITLE
Hibernation

### ISSUE THREAD

**Issue by josephnz** [openzfs/openzfs-docs#157]
@ne9z, I have the following issue with the Arch Linux Root on ZFS HOWTO:
Can you please include the steps to enable hibernation with encrypted bootpool ?

**Comment by mskarbek** [comment]
https://twitter.com/nabijaczleweli/status/1378679960408371207
@nabijaczleweli

**Comment by nabijaczleweli** [comment]
heh, yeah. i say this with as much sincerity as i can muster: if you have to ask, the answer is "you can't resume off zvols"

(and if you recreate what i did there, you have a fifty-fifty chance of it either not working or raking your pool each time you try if you so much as breathe at it wrong. I permanently damaged that pool more times than I can count, so, I repeat: do *NOT* do it on a pool you can't can)

**Comment by josephnz** [comment]
just to clarify, I have a separate swap partition as described in the document. Are you saying it's still a no go? If so perhaps the document should be modified. For eg: currently it says 
"Adjust the swap partition size to your needs. If **hibernation is needed**, swap size should be same or larger than RAM"

**Comment by ne9z** [comment]
If you have created a separate swap partition during installation and enabled encryption, you need to 

- encrypt boot pool with LUKS1, [see here](https://openzfs.github.io/openzfs-docs/Getting Started/Arch Linux/Arch Linux Root on ZFS.html#optional-configuration)
- encrypt swap partition with LUKS2 and add kernel cmdlines, [see here](https://github.com/openzfs/openzfs-docs/blob/e70da303a3dfee4a279ba9f3c0e51549ff3fdcec/docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.rst#hibernation)

I removed the hibernation section as the guide is getting too long ;-)

**Comment by ne9z** [comment]
@nabijaczleweli I guess you are doing swap on zvol.

- zvol in general is extremely patchy, see [1](https://github.com/openzfs/zfs/issues/11407) and other issues, it should be avoided at all cost.
- swap on zvol is known to crash the system, see [here](https://github.com/openzfs/zfs/issues/7734)
- resume hibernation from a pool will corrupt it, this is [known](https://github.com/openzfs/zfs/issues/260)

This guide does not use ZFS for swap at all, for reasons described above. It creates a randomly encrypted swap partition by default and the user can optionally switch to persistent (LUKS2) encryption in [optional configuration](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.html#optional-configuration) section.

After switching LUKS2 for swap, it is possible to enable hibernation (suspend to disk).

**Comment by ne9z** [comment]
Also note that hibernation might not work on some hardware.

- HP EliteBook 820 G3, i3 6100U, integrated Intel Graphics, works
- HP EliteBook 735 G5, R5 2500U, integrated Radeon Vega 8 Graphics, black screen on resume

Basically resume from hibernation only works on integrated Intel graphics. Expect trouble if you are using discrete graphics or AMD APU. This is not specific to this guide - stock Ubuntu installation on ext4 also has these problems.

**Comment by josephnz** [comment]
Thanks for the link, that was it, I can now hibernate onto the swap partition on my Toshiba MIIX 720 with Intel GPU. Thanks once again. On 30 Apr 2021 16:02, ne9z ***@***.***> wrote:
If you have created a separate swap partition during installation and enabled encryption, you need to
encrypt boot pool with LUKS1, [see here](https://openzfs.github.io/openzfs-docs/Getting Started/Arch Linux/Arch Linux Root on ZFS.html#optional-configuration)encrypt swap partition with LUKS2 and add kernel cmdlines, see here
I removed the hibernation section as the guide is getting too long ;-)

**Comment by ne9z** [comment]
I've opened a pull request to add this instruction back, among other improvements. #160
