### ISSUE TITLE
Suggestion use linux-lts

### ISSUE THREAD

**Issue by josephnz** [openzfs/openzfs-docs#162]
@ne9z, I have the following recommendation with the Arch Linux Root on ZFS HOWTO. In step 16 under section preparations, why not choose linux-lts ? For anyone using zfs-dkms, linux-lts maybe a better choice. I have opted to use zfs-dkms.   I have both linux-lts and linux variants installed, however with yesterday's update to 5.12 the zfs module failed to build as the current version of zfs does not support kernel 5.12. I agree that the zfs-dkms section lists the potential issues in the list of disadvantages. However, with a default linux-lts kernel the risk is minimal.

**Comment by ne9z** [comment]
- Arch Linux uses `linux` by default
- In the root on ZFS installation guide, `zfs-linux` is used package by default, using `zfs-dkms` is your choice and thus not covered
- For 5.12, I suggest you try `zfs-dkms-git` package for the time being

@rlaager Please close this issue, won't fix.

**Comment by ne9z** [comment]
Just tested `zfs-dkms-git` package, works with 5.12:
```
[root@archonzfs /]# pacman -S linux linux-headers zfs-dkms-git
:: linux is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-headers is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
resolving dependencies...
looking for conflicting packages...
:: zfs-dkms-git and zfs-linux are in conflict (zfs). Remove zfs-linux? [y/N] y
:: zfs-utils-git and zfs-utils are in conflict. Remove zfs-utils? [y/N] y

Packages (9) dkms-2.8.4-1  lsb-release-1.4-18  pahole-1.21-1  zfs-linux-2.0.4_5.11.16.arch1.1-1 [removal]  zfs-utils-2.0.4-1 [removal]  zfs-utils-git-2021.04.30.r6791.gc903a756a-1  linux-5.12.1.arch1-1
             linux-headers-5.12.1.arch1-1  zfs-dkms-git-2021.04.30.r6791.gc903a756a-1
...
(5/7) Install DKMS modules
(5/7) Install DKMS modules
==> dkms install --no-depmod -m zfs -v git -k 5.12.1-arch1-1
==> depmod 5.12.1-arch1-1
...
```
**Warning**: `zfs-dkms-git` is built directly from [ZFS master branch](https://github.com/openzfs/zfs/tree/master), although well tested, it still might contain bugs.

**Comment by josephnz** [comment]
Thanks for the suggestion and testing. However, I will wait for the 'stable' version. Fortunately, I had both LTS and standard kernel installed, and  I can boot into the LTS kernel ( LTS is the default when you have both) . However for someone just having the standard 5.11, yesterday's 5.12 kernel would have rendered the system unbootable IF they chose to go the dkms route like me. On 7 May 2021 18:03, ne9z ***@***.***> wrote:
Just tested zfs-dkms-git package, works with 5.12:
***@***.*** /]# pacman -S linux linux-headers zfs-dkms-git
:: linux is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
:: linux-headers is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
resolving dependencies...
looking for conflicting packages...
:: zfs-dkms-git and zfs-linux are in conflict (zfs). Remove zfs-linux? [y/N] y
:: zfs-utils-git and zfs-utils are in conflict. Remove zfs-utils? [y/N] y

Packages (9) dkms-2.8.4-1  lsb-release-1.4-18  pahole-1.21-1  zfs-linux-2.0.4_5.11.16.arch1.1-1 [removal]  zfs-utils-2.0.4-1 [removal]  zfs-utils-git-2021.04.30.r6791.gc903a756a-1  linux-5.12.1.arch1-1
             linux-headers-5.12.1.arch1-1  zfs-dkms-git-2021.04.30.r6791.gc903a756a-1
...
(5/7) Install DKMS modules
(5/7) Install DKMS modules
==> dkms install --no-depmod -m zfs -v git -k 5.12.1-arch1-1
==> depmod 5.12.1-arch1-1
...

Warning: zfs-dkms-git is built directly from ZFS master branch, although well tested, it still might contain bugs.

**Comment by ne9z** [comment]
If the you are inclined to ticker with the system, it's recommended to install a boot environment manager:
```
cd $(mktemp -d)
curl -O https://gitlab.com/m_zhou/bieaz/uploads/72a43342d01a6c7c5c8a3669dbc935ba/bieaz-0.2.14-1-any.pkg.tar.zst
curl -O https://gitlab.com/m_zhou/rozb3-pac/uploads/4151f11cf023a7e2246941dc0a0a0643/rozb3-pac-0.3.2-1-any.pkg.tar.zst
pacman -U *
```

This way if anything went wrong you could just rollback in the GRUB menu.

**Comment by josephnz** [comment]
Thanks for that, I already have boot environment manager installed as well, so kinda double insurance 🙂.  All in all the installation instructions are excellent and imo should suit most requirements. I was just wondering if LTS kernel  should be the default recommend kernel in the document, but after reading your earlier  response I agree that it need not be. DKMS users like me should excercise a bit more caution by opting for one or more recovery/fallback methods should the module build fail. On 7 May 2021 18:43, ne9z ***@***.***> wrote:
If the you are inclined to ticker with the system, it's recommended to install a boot environment manager:
cd $(mktemp -d)
curl -O https://gitlab.com/m_zhou/bieaz/uploads/72a43342d01a6c7c5c8a3669dbc935ba/bieaz-0.2.14-1-any.pkg.tar.zst
curl -O https://gitlab.com/m_zhou/rozb3-pac/uploads/4151f11cf023a7e2246941dc0a0a0643/rozb3-pac-0.3.2-1-any.pkg.tar.zst
pacman -U *

This way if anything went wrong you could just rollback in the GRUB menu.

**Comment by ne9z** [comment]
That's fine.

Tip: if not using AUR helper, you should run the above command to upgrade boot environment manager.
An update has been released yesterday.

**Comment by josephnz** [comment]
Yup, I have already (yay) . Thanks.On 7 May 2021 20:24, ne9z ***@***.***> wrote:
That's fine.
Tip: if not using AUR helper, you should run the above command to upgrade boot environment manager.
An update has been released yesterday.
