### ISSUE TITLE
I tried ubuntu boot using ZFS on Raspberry Pi 3 -- results as requested to @rlaager

### ISSUE THREAD

**Issue by dshuman52** [openzfs/openzfs-docs#168]
@rlaager, I have the following issue with the Ubuntu 20.04 Root on ZFS for Raspberry Pi HOWTO:

Instructions are generally great a few issues are noted in the documented steps I followed

I tried installation on a Raspberry PI 3 with a non functional wireless.  You asked for feedback containing @rlaager for those that tried.  Summary I managed to logon ubuntu for the first time and get to the password change prompt then the putty session from windows closed.  There was also a putty session closure after the entry of the userid ubuntu on the first logon attempt.

Thanks, I will be trying this again using a raspberry pi 4 soon.

Steps I followed.

[ubuntu ZFS boot in Raspberry pi 3.txt](https://github.com/openzfs/openzfs-docs/files/6549371/ubuntu.ZFS.boot.in.Raspberry.pi.3.txt)

**Comment by rlaager** [comment]
Thanks for the report. I don't have anything to say about why the logins aren't working; that's probably not ZFS-related. I'll go ahead and close this since there doesn't seem to be an action item here. If you have more to add, let me know.

**Comment by dshuman52** [comment]
I doubt it is ZFS related too as I have not tried to setup the ZFS partition yet,

    On Wednesday, May 26, 2021, 4:52:13 PM EDT, Richard Laager ***@***.***> wrote:  
 
 


Thanks for the report. I don't have anything to say about why the logins aren't working; that's probably not ZFS-related. I'll go ahead and close this since there doesn't seem to be an action item here. If you have more to add, let me know.

**Comment by dshuman52** [comment]
After switching to plain Raspberry Pi imager installs for both 64 and 32 bit I learned this morning about the fake left break right move in the Ununtu installer.  I misread the prompt after the required password change message and instead of entering the CURRENT password to start the password change I jumped to the new password by mistake.  This was totally a user error and I am the user.

**Comment by dshuman52** [comment]
Once I fixed MY password problem I managed to complete through step 6.  I did no no encryption, I separated the temp directory and at this time passed only on the desktop addition in the step 6 options.  There were some questionable messages (noted in the attached text) but in the end after the step 6.6 reboot I could log in.

[Ubuntu XFS root raspi3 steps 2 - 6 with final reboot splash screen.txt](https://github.com/openzfs/openzfs-docs/files/6556049/Ubuntu.XFS.root.raspi3.steps.2.-.6.with.final.reboot.splash.screen.txt)

**Comment by rlaager** [comment]
The ubuntu group thing is normal when you delete a user. That's just saying you deleted the last member of the group (and in this case, that's because it's the user's private group).

The cryptsetup message is normal. The "root device does not exist" is probably fine. I'm not sure about that timeout.

I'm not sure about the "Operation was interrupted" message. That's weird if you didn't Ctrl-C it. But if you re-ran it, it should be fine. Though I see that recurred again.
