### ISSUE TITLE
ubuntu 20.04 and odroid xu4

### ISSUE THREAD

**Issue by heapxor** [openzfs/openzfs-docs#171]
Hello,
is it possible to replicate similar steps on odroid XU4 and run while utilizing ZFS as rootfs? I assume there is no way to somehow migrate ext4 roofs from running installation to ZFS? Is it at least possible to setup ZFS as rootfs utilizing ubuntu install image for xu4? 

thanks

**Comment by rlaager** [comment]
I’d imagine you could do something similar to the Raspberry Pi instructions.

There is no way to migrate and ext4 filesystem _in place_ (like btrfs can/could do.)

If there is available space at the end of the disk (or if you can make it by using e2resize to shrink the ext4 filesystem), you can put ZFS in that space. This only works if you have at least as much space as is used. However, this means the ZFS is at the end and the space where the ext4 filesystem was ends up being wasted. That’s why I move the ext4 to the end first and then put ZFS at the beginning. That way, once the conversion is done, the ext4 can be thrown away and the ZFS expanded.

If you want to convert the system in place (as opposed to the filesystem) and if the disk is less than 50% full, you could: 1) Shrink the ext4 filesystem then its partition. 2) Create a new partition and ext4 filesystem in the second half of the disk. 3) Copy everything to the new ext4 and switch to booting off it. Reboot. 4) Destroy the old ext4, replace with ZFS, copy everything to it, and switch to booting off it. Reboot. 5) Destroy the ext4, expand the ZFS partition, and expand the zpool.
