### ISSUE TITLE
zsh usage during boot guide has issues with [ rather than [[

### ISSUE THREAD

**Issue by paulhargreaves** [openzfs/openzfs-docs#172]
[https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/3-system-configuration.htm]( https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/3-system-configuration.html)

Installing arch this way, I'm using 2021-06-01 (rather than 05-01) and the default shell appears to be zsh.
zsh requires all if [ ] to be if [[ ]].

**Comment by ne9z** [comment]
Please review [preparation](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/1-preparation.html), bash shell is explicitly required. Other shell is not supported by this guide.

**Comment by paulhargreaves** [comment]
Sure, but if that one single change is made (twice, two different if statements) then the out-of-the-box shell works fine.

**Comment by ne9z** [comment]
I get it, only this change is required to make this guide compatible
with zsh.

But as I'm commited to maintain this guide and only use bash
shell, I can unfortunately not test zsh compatibility.

You are more than welcome to review future changes and ensure
compatibility with zsh. :-)

**Comment by paulhargreaves** [comment]
Heh, sure, happy to help. I've had multiple arch installs for a while now with zfs, this was my first run through booting. 

FYI 2021.6.1 iso also works, with latest kernel etc.

**Comment by richardelling** [comment]
FWIW, the only reason to use '[' is if you're running sh, not bash. Most shell style guides recommend or require the '[[' to be used for those shells that support it (bash, ksh, zsh). Unfortunately, OpenZFS does have a requirement for sh support for some tests. Until this changes, the confusion and angst around '[' will continue.

IMNSHO if you're requiring and only supporting bash, then you should also require '[['

**Comment by ne9z** [comment]
@richardelling Thanks for the reply.

I used [ primarily out of habit. Due to my previous experience with Alpine, which only has busybox sh by default, I mostly write POSIX-compliant shell scripts.

Of course this is not a useful argument, as arrays, which is used in the guide, is also not supported by POSIX.

Would you post a link to the drawback of not using `[[`?
