### ISSUE TITLE
ZFS Encrypton on boot missing how to change the password(s)

### ISSUE THREAD

**Issue by paulhargreaves** [openzfs/openzfs-docs#173]
There are two different places we are asked to enter keys:

[https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/2-system-installation.html](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/2-system-installation.html
)and
[https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/4-optional-configuration.html](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/4-optional-configuration.html)

I _assume_ the passwords can be different, but it's not clear if they should be, or if it doesn't matter.
It's not clear how to change the passwords after install, and any implications on if they are changed.

It's also not clear why there are two keys being loaded into the cryptsetup?

**Comment by ne9z** [comment]
>  the passwords can be different, but it's not clear if they should be

Yes, the passwords can be different, they are not related in anyway.

> It's not clear how to change the passwords after install

It is not the purpose of this guide to cover how to use ZFS, please refer to [ZFS man page](https://openzfs.github.io/openzfs-docs/man/8/zfs-change-key.8.html) if boot pool is not encrypted, or [cryptsetup man page](https://linux.die.net/man/8/cryptsetup) if boot pool is encrypted.

> any implications on if they are changed

No implication, you can change the passphrase anytime.

> It's also not clear why there are two keys being loaded into the cryptsetup?

When boot pool is encrypted, boot sequence is:
- You enter a passphrase in GRUB, boot pool is decrypted
- Boot pool contains initrd
- initrd contains key files for root pool and boot pool
- GRUB loads initrd
- initrd decrypts root pool and boot pool with key files

So there are two keys for boot pool, one passphrase, one key file.

If we do not generate the key files, the boot sequence will be the following:
- You enter a passphrase in GRUB, boot pool is decrypted
- Boot pool contains initrd
- initrd does not contain key files
- GRUB loads initrd
- initrd asks for root pool passphrase
- initrd asks for boot pool passphrase

**Comment by paulhargreaves** [comment]
Thanks. I'm already using zfs encryption on a couple of hosts, but wanted to make sure that changing the zfs key had no adverse impact. 

Not played much with cryptsetup, but have just successfully added and removed a new passphrase. 

And thanks for the explanation, that makes it a lot clearer.
