### ISSUE TITLE
Upgrading Root on ZFS from Ubuntu 18.04 to 20.04?

### ISSUE THREAD

**Issue by carlreinke** [openzfs/openzfs-docs#18]
Looking though the documentation for 20.04, I see that there have been some significant changes from 18.04 -- for example, legacy mount points are no longer necessary.

I have a Ubuntu machine that I set up following the Ubuntu 18.04 Root on ZFS guide, and everything went smoothly when I upgraded Ubuntu to 20.04.  Naturally, everything is still set up according to the 18.04 guide.  With a lot of trial-and-error, I'm sure I could rework it to mostly look like what you'd get from running the 20.04, but it would be better to have someone who actually knew what they were doing provide some guidance.

Or should I just leave it the way it is?

**Comment by rlaager** [comment]
It's unclear to me what version you are currently running.
* If you are asking about changing a 18.04 system to follow the 20.04 setup while still being 18.04, absolutely do not.
* If you are asking about changing a 20.04 system setup according to the 18.04 guide to be like the 20.04 guide, you could do most of that with some work. The part you can't really change without reinstalling is the partitioning. That said, if I was in this situation, I'd either leave it (if things are working to your satisfaction) or reinstall completely from scratch.
* If you are asking about upgrading an 18.04 system to 20.04, you have a couple of options. At the one extreme, you could just upgrade in place. That will likely work fine. At the other extreme, you could reinstall from scratch and restore your data from a backup. That is what I personally do for all upgrades, whether ZFS is installed or not. It gives me a good opportunity to remove cruft from experimenting. In the middle, you could create new datasets that follow the 20.04 model and install into those, leaving the partitions and pools as is. This should work, assuming you have a bpool and an ESP partition already.

I'm going to close this. If this doesn't address your question, please feel free to comment and I can re-open it. I don't believe it prevents you from commenting when I close (as long as I don't lock). In the event that it does lock you from commenting, drop me an email: rlaager@wiktel.com

**Comment by cheesycod** [comment]
Another thing about upgrading: You no longer really need the guide with the ZFS installer now builtin to Ubuntu 20.04

**Comment by Rydako** [comment]
> Another thing about upgrading: You no longer really need the guide with the ZFS installer now builtin to Ubuntu 20.04

Not really true at the moment. The 20.04 installer is very barebones right now, and so the 20.04 guide compliments it really well. The guide allows for manual installs, allowing users to fill the gaps the canonical implementation has, while also ensuring they result in a supported implementation (keeping zsys support)
