### ISSUE TITLE
HTTP 404 error

### ISSUE THREAD

**Issue by ith140** [openzfs/openzfs-docs#182]
@ne9z, I have the following issue with the Arch Linux ZFS HOWTO:
```
8. Ignore kernel updates:

sed -i 's/#IgnorePkg/IgnorePkg/' /mnt/etc/pacman.conf
sed -i "/^IgnorePkg/ s/$/ ${INST_LINVAR} ${INST_LINVAR}-headers zfs-${INST_LINVAR} zfs-utils/" /mnt/etc/pacman.conf

Kernel will be updated manually. See here.
```

The link at the end (here) does not work.

I've followed your walkthrough and got my system up and running, so thanks for all your hard work! The only thing I would benefit from is understanding a little bit about how to deal with NVIDIA (you don't have to answer if it's painful). The archzfs repo seems to not have the kernel headers, so I can't get the discrete card working yet. I assume this means I need to use a different approach - am I better off with zfs-linux, or zfs-dkms or am I missing something?

Thanks if you can share some knowledge!

@ith140

**Comment by ne9z** [comment]
That link should be pointing to [here](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/1-zfs-linux.html#update-kernel), thanks for the notice.

Kernel headers have nothing to do with ZFS: it is provided as a companion package to the kernel. You can install the kernel package by following instructions given [here](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/2-zfs-dkms.html) **up to _Install zfs-dkms_**. You can use NVIDIA module alongside `zfs-linux`, `zfs-dkms` is not necessary.

I recommend you to stick with `zfs-linux` as it seems that you are unfamiliar with DKMS modules.

**Comment by ne9z** [comment]
And I strongly recommend you to install `bieaz` boot environment manager and its pacman hook `rozb3-pac` from AUR before trying to fix NVIDIA support - I have received reports where including NVIDIA module broke the entire installation.
