### ISSUE TITLE
Debian Bullseye Root on ZFS

### ISSUE THREAD

**Issue by freezed** [openzfs/openzfs-docs#204]
Hi team, thanks for all the job.

Debian/Bullseye was [recently released as stable](https://www.debian.org/News/2021/20210814) and the howto «_Debian Bullseye Root on ZFS_» is missing.

**Comment by gmelikov** [comment]
Closed via https://github.com/openzfs/openzfs-docs/commit/b81a4719398f5ac305249bef4f33f96d7a13b7ca

**Comment by rlaager** [comment]
@gmelikov heh, I'm finally actually working on this today.
