### ISSUE TITLE
Questions about Debian initrd documentation

### ISSUE THREAD

**Issue by Yvan-Masson** [openzfs/openzfs-docs#215]
Hi,

Thanks for documenting OpenZFS. I am experimenting on a fresh Bullseye VM with root on ZFS, following the current PR #205. Grub is installed in BIOS mode and there is only one disk. System works properly, but the current [Debian initrd documentation](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20GNU%20Linux%20initrd%20documentation.html) does not match what I have:

1. The Grub linux command line in the "Booting from snapshot" section is different. If we remove the snapshot mentioned to have the original line, the doc gives :
```
linux   /ROOT/debian-1@/boot/vmlinuz-3.2.0-4-amd64 root=ZFS=rpool/ROOT/debian-1 ro boot=zfs $bootfs quiet
```
While on my system it is:
```
linux   /BOOT/debian@/vmlinuz-5.10.0-9-amd64 root=ZFS=/ROOT/debian ro root=ZFS=rpool/ROOT/debian quiet
```
Maybe it is just Grub that is much newer in Bullseye than in the documentation?

2. The doc says it should be possible to select snapshot dynamically by adding `@` only to the `root` parameter. In my case, system just hangs after `Loading initial ramdisk ...`

3. I tried a rollback from snapshot by specifying the snapshot name in the `root` parameter and by adding `rollback=1`. System then hangs (see picture below). After enforcing a reset, system boot properly on the previously selected snapshot. Maybe this could be better explained in the documentation?
![snapshot_rollback](https://user-images.githubusercontent.com/9531149/137141894-0e01820f-71f4-40f4-9c15-b83d36fc63fd.png)

Regards,
Yvan

**Comment by rlaager** [comment]
The Root on ZFS HOWTOs use a separate bpool and have for a while now. I didn't write those other docs. I've made some minor tweaks to bring it closer.
