### ISSUE TITLE
CentOS 8.4 zfs-dkms guide doesn't work

### ISSUE THREAD

**Issue by babarnescocke** [openzfs/openzfs-docs#216]
Doing some testing on AWS Lightsail and it turns out the adjustment in docs to use 
`source /etc/os-release` and grab version from there doesn't work on a stock CentOS 8 image.

If you just copy paste from the guide you get 
`[MIRROR] zfs-release.el8.noarch.rpm: Status code: 404 for https://zfsonlinux.org/epel/zfs-release.el8.noarch.rpm (IP:*.*.*.*)`

on a fully patched CentOS 8.4 VM:
`cat /etc/centos-release
CentOS Linux release 8.4.2105`

**Comment by steakknife** [comment]
Yeap, totally broken on CentOS.

Also it needs to be tested on other RHEL/OEL EL-compatible systems which aren't going away anytime soon. Download the RH iso, install it to a vm, throw it in there.
