### ISSUE TITLE
Root on ZFS Raspberry Pi instructions should include USB SSDs

### ISSUE THREAD

**Issue by scott-ainsworth** [openzfs/openzfs-docs#217]
The `Ubuntu 20.04 Root on ZFS for Raspberry Pi` instructions should work for both microSD cards and USB SSDs.

I have created a preliminary version of the instructions for installing on both microSDs and USB SSDs. Before I create a Pull Request, additional testing and review would be greatly appreciated.

https://github.com/scott-ainsworth/openzfs-docs/blob/usb-ssd/docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS%20for%20Raspberry%20Pi.rst

Thanks,
Scott

**Comment by gmelikov** [comment]
Closed via #218
