### ISSUE TITLE
zfs root install script

### ISSUE THREAD

**Issue by vasile-gh** [openzfs/openzfs-docs#226]
Hi guys, just thought I would let you know that I posted a script to build a basic Debian system with zfs root here on github.

https://github.com/vasile-gh/debian-zfs-root-script

If you think it's worth posting a link to it in the Debian section here, feel free to do so.

Regards

**Comment by rlaager** [comment]
There have been a number of install scripts built by various people over the years. The documentation is currently for a manual process. I'm happy to keep it that way, unless or until we get this support into an installer application itself (which would be the best).
