### ISSUE TITLE
Invalid vdev specification

### ISSUE THREAD

**Issue by skibbipl** [openzfs/openzfs-docs#23]
Hello,
I'm trying to install debian on ZFS pool. So I'm following debian buster steps, but I'm stuck on `Create the boot pool`. When I execute the command I get following error:
```
invalid vdev specification
use '-f' to override the following errors:
/dev/disk/by-id/nvme-XXXX-part3 contains a filesystem of type 'swap'
```
According to parted filesystem type of partition 3 is swap indeed:
```
root@debian:~# parted $DISK
GNU Parted 3.2
Using /dev/nvme1n1
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p
Model: KBG30ZMV256G TOSHIBA (nvme)
Disk /dev/nvme1n1: 256GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End     Size    File system     Name  Flags
 2      1049kB  538MB   537MB   fat32                 boot, esp
 3      538MB   1612MB  1074MB  linux-swap(v1)
 4      1612MB  256GB   254GB
```
Also according to Arch wiki `-o ashift=12` is for disks with 4096 sector size. But my nvme drive shows 512b so perhaps I should use `-o ashift=9`?

**Comment by rlaager** [comment]
`parted` isn't so great for gpt, as it doesn't show the types in its print output. I'm sure there is some way to get that. `gdisk` is better in that regard.

In any event, it looks like you ran `mkswap` on that third partition (or that area on disk was previously used for swap). Personally, I'd just zero the whole disk and start over.

**Comment by skibbipl** [comment]
I haven't run any additional steps. No `mkswap` at all. Will try again, but I'm not sure if this will change anything.

**Comment by rlaager** [comment]
It's possible that area on disk was used for swap before. If you zero the whole disk, that will clear that up. If your NVMe disk supports TRIM (which it most likely does), you could **(warning:) zero the entire device with:** `blkdiscard /dev/nvme1n1`

**Comment by skibbipl** [comment]
This gave me thinking - I had previously installed ubuntu on that disk but I thought that `sgdisk --zap-all` is enough to wipe all previous partition information. Will try the full wipe.

**Comment by rlaager** [comment]
`sgdisk --zap-all` will delete all the partition table entries. But a partition table is just a map saying a particular range on disk is partition 1, another range is partition 2, and so forth. The data on disk doesn't change if you delete a partition table entry. You can delete a partition (in e.g. parted or gdisk), save it, then recreate the partition with the same exact values and the data is still there.

**Comment by skibbipl** [comment]
You're absolutely right. I just wiped the drive and everything went smothly.
