### ISSUE TITLE
restore ESP partition mirror

### ISSUE THREAD

**Issue by shribe** [openzfs/openzfs-docs#236]
Ubuntu 20.04, server configured with mirrored disks, as per: https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html

I would like to automate disk replacement as much as possible. After replacing a failed disk, creating partitions, running `zpool replace`, is there a command-line equivalent to running `dpkg-reconfigure grub-efi-amd64` and selecting the new disk to get grub installed? (I do not need to change any of the other options.)

**Comment by rlaager** [comment]
Is the question how to either A) automated dpkg-reconfigure or B) do the equivalent of `dpkg-reconfigure grub-efi-amd64`? I'd imagine either is possible.

For A, I'd look into using `debconf-set-selections` to set whatever the devices setting is and `dpkg-reconfigure -fnoninteractive grub-efi-amd64` to apply it.

For B (doing it manually), you're probably looking at doing a `grub-install` plus some things to mirror over the EFI System Partition (ESP).

**Comment by shribe** [comment]
For anyone coming across this in the future, this does exactly what I want:

```
cat <<- EOF | debconf-set-selections -v
grub-efi-amd64 grub-efi/install_devices multiselect <path-to-part1>, <path-to-part2>
grub-efi-amd64 grub-efi/install_devices_disks_changed multiselect <path-to-part1>, <path-to-part2>
EOF

dpkg-reconfigure -fnoninteractive grub-efi-amd64
```
