### ISSUE TITLE
[Security] Workflow publish.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Ale0x78ButInBinary** [openzfs/openzfs-docs#241]
The workflow publish.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by gmelikov** [comment]
Thank you, bumped it in https://github.com/openzfs/openzfs-docs/commit/d1fe488e56072353550010076790ac0717150700 just to be sure (we had it only in one action, and only in this repository).

But honestly, I don't see how https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839 applies to v1, original code was indroduces in v2.
