### ISSUE TITLE
Boot partition `zpool create` uses inconsistent option parameters

### ISSUE THREAD

**Issue by jroedel** [openzfs/openzfs-docs#248]
@rlaager, I have the following issue with the Ubuntu 20.04 Root on ZFS HOWTO:

Maybe it doesn't make any difference, but I noticed that on Step 2.7 the following code
```
zpool create \
    -o cachefile=/etc/zfs/zpool.cache \
    -o ashift=12 -o autotrim=on -d \
    -o feature@async_destroy=enabled \
    -o feature@bookmarks=enabled \
    -o feature@embedded_data=enabled \
    -o feature@empty_bpobj=enabled \
    -o feature@enabled_txg=enabled \
    -o feature@extensible_dataset=enabled \
    -o feature@filesystem_limits=enabled \
    -o feature@hole_birth=enabled \
    -o feature@large_blocks=enabled \
    -o feature@lz4_compress=enabled \
    -o feature@spacemap_histogram=enabled \
    -O acltype=posixacl -O canmount=off -O compression=lz4 \
    -O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
    -O mountpoint=/boot -R /mnt \
    bpool ${DISK}-part3
```
uses lower case `-o` for most lines, but in the last 3 lines uses capital `-O`.

I have a problem installing the efi, that's why I'm looking for anything that could affect it. I'll post a separate issue for my problem.

**Comment by scott-ainsworth** [comment]
Capital *O* and lower case *o* are two different options.  Lower case *o* sets pool properties.  Capital *O* sets file system properties.  I think of it this way: if for a non-ZFS filesystems the property could be set in /etc/fstab, it is probably capital capital *O*.  If it needed to be set by mkfs, it is most likely lower case *o*.

**Comment by jroedel** [comment]
Ahh ok, that makes sense. Thanks for the quick response!

Also, I was able to fix my issue last night. I noticed that copying/pasting multiple commands usually works except when it's apt. It seems apt kills the paste buffer. That contributed to me skipping over a couple commands in the setup. Haste makes waste I guess haha

Thanks for your hard work on this great project!
