### ISSUE TITLE
FAQ - broken link to "Setting up the /etc/zfs/vdev_id.conf file"

### ISSUE THREAD

**Issue by sbraz** [openzfs/openzfs-docs#250]
Hi,
I don't really understand why but it looks like the link from this sentence is invalid in the rendered doc (see https://openzfs.github.io/openzfs-docs/Project%20and%20Community/FAQ.html#selecting-dev-names-when-creating-a-pool-linux):
> To configure this file please refer to section Setting up the /etc/zfs/vdev_id.conf file

It points to https://openzfs.github.io/openzfs-docs/Project%20and%20Community/FAQ.html#setting-up-the-etczfsvdev_idconf-file although the correct anchor is apparently https://openzfs.github.io/openzfs-docs/Project%20and%20Community/FAQ.html#setting-up-the-etc-zfs-vdev-id-conf-file.

This is weird because the RST seems to be correct and the link works on GitHub: https://github.com/openzfs/openzfs-docs/blob/master/docs/Project%20and%20Community/FAQ.rst#selecting-dev-names-when-creating-a-pool-linux

**Comment by gmelikov** [comment]
Thank you, fixed!
