### ISSUE TITLE
Question: why does the documentation recommend /etc/fstab over zfs-mount-generator for a zfs root?

### ISSUE THREAD

**Issue by savyajha** [openzfs/openzfs-docs#257]
Honestly curious about this, because I saw that an edit was made to the "Root on ZFS" portions of the Arch Linux, Fedora, RH and NixOS through pull request #195 which removed the use of `zfs-mount-generator` and opted for a purely `/etc/fstab` based configuration for Arch Linux, Fedora and RH.

I tried searching for a reason for this: I had thought that `zfs-mount-generator` was the preferred way of mounting zfs datasets because it can directly act using zfs properties if the appropriate `/etc/zfs/zfs-list.cache/<pool>` file were to exist. An fstab would have to be edited manually whenever one would wish to change any property of a zfs dataset, I would assume. However, I was unable to find a justification for this change. What issues remain with `zfs-mount-generator`, and can they be added to the docs for curious people like me?

**Comment by ne9z** [comment]
This has to do with the scenario where multiple systems are installed on the same pool.  Consider the following layout:
```
DATASET                CANMOUNT    MOUNTPOINT
rpool/debian/system    noauto      /
rpool/debian/user/me   on          /home/me
rpool/arch/system      noauto       /
rpool/arch/user/me     on           /home/me
```

When using mount generator, both home directory will be present in zfs-list.cache/pool file and system will attempt to mount both dataset on boot, on the same path.

When using fstab, we can actually control who ends up in fstab on a per-system basis.

Another reason is the mounting of boot dataset, where we need to mount it at /boot despite canmount=noauto, just like the system dataset. This is not doable with mount-generator, so fstab is used.

**Comment by savyajha** [comment]
Ah. My understanding was that everything under `rpool/DATA/` was common between different boot environments and one would select the boot environment to use using the `root=rpool/ROOT/<dataset name>` argument in grub entries/EFI bootloader entries. That way you would only separate out the common datasets into `rpool/DATA` and keep everything you don't want shared in `rpool/ROOT/debian` or `rpool/ROOT/arch` or whatever.

But that breaks if you want a separate `/var/log`, for example, which you obviously would.

Thanks for the explanation! I understand the reasoning behind it properly now.
