### ISSUE TITLE
Arch on ZFS - additional instructions for Secure Boot

### ISSUE THREAD

**Issue by little-helper-001** [openzfs/openzfs-docs#266]
Hi there,

I followed your very nice guide to setup Arch on a ZFS root. I however are unable to enable Secure Boot. It seems I am not understanding the process good enough to adapt the [instructions from the Arch Wiki for setting up Shim ](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim) to the environment your guide sets up. I thought I had everything ready to go multiple times but end up with missing or invalid signatures on every try.

Might one of you may be able to provide the specific commands to run in the environment the guide sets up.

Thanks in advance.

**Comment by little-helper-001** [comment]
> There's nothing specific to a system set up by this guide. If a method of enabling Secure Boot works on other situations, it should work here also.

I see this differently. The first part of the instructions, until creating the new entry for shim in the UEFI using `efibootmgr`, from the wiki can be followed and applied pretty much as they are. The mok manager starts up and asks for the key to be enrolled into Shim. The problem is the following part.
```
# grub-install --target=x86_64-efi --efi-directory=esp --modules="tpm" --sbat /usr/share/grub/sbat.csv
# sbsign --key MOK.key --cert MOK.crt --output esp/EFI/GRUB/grubx64.efi esp/EFI/GRUB/grubx64.efi
# cp esp/GRUB/grubx64.efi esp/boot/grubx64.efi
```
This can not applied at all. The grub install command is different from the ones used in the guide and installs to a different directory. The sbsign command can not be applied because while at this point two grubx64.efi files should exists neither is in the path given. The last command is also a mystery to me since esp/GRUB does not exist at all and I have no idea where to copy things. If those last commands would be fixed precise commands could totally be given for the guide.

Also it is important to note that with Shim you can't brick your system. The idea is that shim is signed with the Microsoft keys that come pre-installed on most systems, the keys don't get enrolled into the UEFI but into the Shim pre-loader. The UEFI loads Shim with the Microsoft key and Shim loads the other binaries with the self created key.

As I said I am totally lost what the idea is behind these last commands. I tried to adapt them but it seems I am missing something because the chain of trust cannot be established when I try to boot.

**Comment by Reuenthal767** [comment]
Hey @little-helper-001 do you still have that guide around? I'm gonna need to enable secure boot on a Thinkpad, I've just finished my zfs with encrypted bpool and it would be great to have some guidance :pray:

**Comment by little-helper-001** [comment]
@Reuenthal767 I followed the [OpenZFS guide for ZFS on Root on Arch](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/index.html#root-on-zfs). After Installation I followed (following this guide requires you do make some adaptions) the Arch wiki guide on setting up [secure boot via the shim boot loader](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim). If you don't manage to set it up yourself let me know.

**Comment by ne9z** [comment]
@gmelikov This  issue can be closed.  The section on Secure Boot was deprecated and the user is advised to seek information on Arch Linux wiki instead.
