### ISSUE TITLE
Add users optional home directory to fstab

### ISSUE THREAD

**Issue by little-helper-001** [openzfs/openzfs-docs#267]
Hi there,
the guide for Arch on root is now based on the `/etc/fstab` mounting the directories on the rpool. However during the optional step to create a home directory for a user the users directory is not added to fstab and because of that not mounted during boot. 

I suggest adding something along the lines of:
```
echo "rpool_${INST_UUID}/${INST_ID}/DATA/default/home/${myUser}    /home/${myUser}    zfs zfsutil,rw,xattr,posixacl    0 0" >> /etc/fstab
```

**Comment by ne9z** [comment]
Thanks for the report! Will fix by moving user dataset creation to an earlier position then generate its fstab entry alongside with other system datasets.
