### ISSUE TITLE
l2arc_exclude_special not detailed in relevant documentation page

### ISSUE THREAD

**Issue by kewiha** [openzfs/openzfs-docs#274]
The Module Parameters page in the Performance and Tuning Section [here](https://github.com/openzfs/openzfs-docs/blob/master/docs/Performance%20and%20Tuning/Module%20Parameters.rst) does not detail the relatively new parameter "l2arc_exclude_special", but arguably it's relevant to performance and tuning.

The l2arc_exclude_special parameter is detailed in [here](https://github.com/openzfs/zfs/blob/master/man/man4/zfs.4) and so most of the information could be snagged from there. 

I can fork and propose edits if you want, but it may be less effort for a reviewer to make the change themselves rather than review my attempt.

**Comment by gmelikov** [comment]
Contributions are welcome, I'd be glad to review your patch.

**Comment by gmelikov** [comment]
Closed via https://github.com/openzfs/openzfs-docs/pull/275
