### ISSUE TITLE
Inconsistancy error in OpenZFS dosumentation - zfs_arc_max

### ISSUE THREAD

**Issue by EHWV** [openzfs/openzfs-docs#285]
On the website of OpenZFS I noticed the following inconsistency error in the documentation. The following two descriptions of the kernel parameter zfs_arc_max are not the same:

1. OpenZFS - Home » Performance and Tuning » Module Parameters » [zfs_arc_max](https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#zfs-arc-max):
<blockquote>
<b>zfs_arc_max</b>
<p>Maximum size of ARC in bytes. If set to 0 then the maximum ARC size is set to 1/2 of system RAM.</p>
</blockquote>

2. OpenZFS - Home » Man Pages » Devices and Special Files (4) » zfs.4 » DESCRIPTION » [zfs_arc_max=0B (ulong)](https://openzfs.github.io/openzfs-docs/man/4/zfs.4.html):
<blockquote>
<b>zfs_arc_max=0B (ulong)</b>
<p>Max size of ARC in bytes. If 0, then the max size of ARC is determined by the amount of system memory installed. Under Linux, half of system memory will be used as the limit. Under FreeBSD, the larger of all_system_memory - 1GB and 5/8 × all_system_memory will be used as the limit. This value must be at least 67108864B (64MB).</p>
</blockquote>

Kind regards,
Eric

(apologies for the spelling errors in the subject title)

**Comment by gmelikov** [comment]
Duplicate of #276
