### ISSUE TITLE
Fail to install ZFS on RH 6

### ISSUE THREAD

**Issue by DmitryLitvintsev** [openzfs/openzfs-docs#29]
Hi, 

I followed these steps:

```
wget http://download.zfsonlinux.org/epel/zfs-release.el6.noarch.rpm
rpm -i zfs-release.el6.noarch.rpm 
```
edited `/etc/yum.repo.d/zfs.repo` to enable `kmod`

Then:

```
yum install zfs
```

But:

```
# modprobe zfs
FATAL: Module zfs not found.
```

And I see that modules got installed in wrong directory:

```
# rpm -ql kmod-zfs
/lib/modules/2.6.32-754.29.1.el6.x86_64
/lib/modules/2.6.32-754.29.1.el6.x86_64/extra
/lib/modules/2.6.32-754.29.1.el6.x86_64/extra/zfs
```

My kernel is 

```
# uname -r
2.6.32-696.23.1.el6.x86_64
```

what can I do? I cannot upgrade the kernel on that machine. This is default kernel for RH 6. 

Thanks, 
Dmitry

**Comment by gmelikov** [comment]
Looks like 2.6.32-754 is the latest kernel version in RHEL6, maybe you've already installed it? https://access.redhat.com/articles/3078

**Comment by cheesycod** [comment]
Try updating your RH6 using "sudo yum update" and rebooting

**Comment by cheesycod** [comment]
Also, you should consider upgrading to RH7 or RH8. That kernel version is old

**Comment by gmelikov** [comment]
Closed as stale, feel free to reopen.
