### ISSUE TITLE
Issue with steps in ZFS install page for Rocky 8.5 Root on ZFS

### ISSUE THREAD

**Issue by wilhelm271** [openzfs/openzfs-docs#292]
Specifically here:  https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/RHEL%208-based%20distro%20Root%20on%20ZFS/5-bootloader.html

The step #2 

Generate initrd:

rm -f /etc/zfs/zpool.cache
touch /etc/zfs/zpool.cache
chmod a-w /etc/zfs/zpool.cache
chattr +i /etc/zfs/zpool.cache
for directory in /lib/modules/*; do
  kernel_version=$(basename $directory)
  dracut --force --kver $kernel_version
done

Consistently returns an error.  Specifically:
**dracut: /lib/modules/4.18.0-348.2.1.el8_5.x86_64//modules.dep is missing. Did you run depmod?**

There is no RAID hardware, only a ZFS mirror of the two boot drives as described in the same setup steps under System Installation.  The bpool and rpool both show as healthy mirrors.  Clearly either I'm missing something (following the steps exactly), or we're missing an essential step prior to step 2.  I tried depmod -a, but it returned an error as well:

depmod: ERROR: could not open directory /lib/modules/4.18.0-348.el8.0.2.x86_64: No such file or directory
depmod: FATAL: could not search modules: No such file or directory

I'm not very familiar with dempod dependencies, so it's likely I am missing something there.

One thing that stands out as curious to me is in the dracut error, there is a double-slash in the path /lib/modules/4.18.0-348.2.1.el8_5.x86_64//modules.dep  Unless that's intentional, it would seem that we're missing a variable, since that path is dynamically generated?

Thanks!

**Comment by ne9z** [comment]
Thanks for reporting the issue.

It is expected that during installation, tons of error messages would be generated.  Most of them are harmless though.

The crucial question is whether your system boots after installation, and if not, what is the symptom.

**Comment by wilhelm271** [comment]
No, it didn't boot on the first try, but it's not clear if this is the reason or not.  I hit it again  on the second install try and decided to pause here in case there was something missing here.

**Comment by ne9z** [comment]
You need to post here the exact symptom of it unable to boot.  I can't help you if I don't know what the problem actually is.

You can have a look at #282, as an example.

**Comment by ne9z** [comment]
Yep.  In #282 the depmod issue was also reported and it did not have any bearing on the actual problem whatsoever.

**Comment by wilhelm271** [comment]
Sounds like a false alarm then, apologies.

One side question.  I notice that in the step for chroot:

echo "INST_PRIMARY_DISK=$INST_PRIMARY_DISK
INST_LINVAR=$INST_LINVAR
INST_UUID=$INST_UUID
INST_ID=$INST_ID
unalias -a
TERM=xterm
INST_VDEV=$INST_VDEV
INST_VDEV=$INST_VDEV
DISK=\"$DISK\"" > /mnt/root/chroot
arch-chroot /mnt bash --login

$INST_LINVAR isn't defined in the steps as it is in some of the other distro steps such as arch linux, which has:  INST_LINVAR=$(sed 's|.*linux|linux|' /proc/cmdline | sed 's|.img||g' | awk '{ print $1 }') 

As for the failure in previous steps, I may have solved it (we'll see) and it might (we'll see) be a PEBCAK, and if so.  Deep apologies and thanks for the time.

**Comment by ne9z** [comment]
INST_LINVAR refers to the kernel variant one wish to install.  This is an Arch-specific option and therefore not used in fedora or rhel: the only choice you have is to install the RedHat supported kernel.

>  Deep apologies and thanks for the time.

No need for apologies!  For me, the only thing matters in a issue report is sincerity, which this issue clearly has.

**Comment by wilhelm271** [comment]
Thanks!

As for the failure, a clean redo to remove the previous pebcak, I still find myself here:

![image](https://user-images.githubusercontent.com/75437805/163050150-084e69e6-cbdc-4cba-9985-11584b6afe7b.png)

**Comment by ne9z** [comment]
Interesting.  I suggest you try booting with **only** mirrored system disks.  Ensure the installation media or any other bootable media are disconnected.

**Comment by ne9z** [comment]
Hello.  The RHEL guide has been updated (see #397) to address the issues. I think this issue can be closed.
