### ISSUE TITLE
reduce the number of options passed to ZFS

### ISSUE THREAD

**Issue by anarcat** [openzfs/openzfs-docs#307]
This is a rather broad question that I brought up in #306, but it seems to me it deserves at least some discussion.

What I wrote in the PR there is:

> In general, I find that this guide suggests too many exotic things, instead of focusing on "just install the thing with ZFS".

Then I went on with some examples:

 * [ ] the `bpool` has a *lot* of settings, not sure they are all relevant (@rlaager suggested using `compatibility=grub2` once that feature lands, but when is that?)
 * [ ] ~~`-O encryption=aes-256-gcm` is the default, AFAIK~~ (actually fixed in 903d6310335ff0715e7620cca87b95774561430f)
 * [ ] `dnodesize=auto` and the xattr stuff are optimisations, maybe they could be left out? or at least regrouped?
 * [ ] there are also a *lot* of mountpoints created, it's a bit excessive

In general, I think those guides are great and do the right thing. But for an experience sysadmin like me, they are a bit scary, because I feel I need to lookup *everyone* of those single settings to see if they apply to me or not. Since many are not necessarily relevant (like `encryption=X` where X is the default), or are opinionated (like #306 AKA `utf8only`), it can be confusing to figure out which settings should be reviewed and why.

When I first followed the guide, I setup my pools with `utf8only` and now I really regret it, because it's a major interoperability concern. Now #306 should fix this in the future, but I wonder how many more of those creep in there.

In general, for actual necessary cases like `xattr`, shouldn't that be made *default* in OpenZFS upstream, so that we eventually *don't* have to know the magic formula?

In my mind, OpenZFS should converge to having basically *zero* custom arguments. Right now, the root pool creation in the bullseye guide is:

       zpool create \
           -o ashift=12 \
           -O acltype=posixacl -O canmount=off -O compression=lz4 \
           -O dnodesize=auto -O relatime=on \
           -O xattr=sa -O mountpoint=/ -R /mnt \
           rpool ${DISK}-part4

I think it should be turned into this:

       zpool create \
           -O canmount=off -O mountpoint=/ -R /mnt \
           rpool ${DISK}-part4

That means, for example:

- [ ]  the `ashift` detection problem is fixed (!?) -- i know how that sounds, but we can dream, can we?
- [ ]  `posixacl` turns on `dnodesize=auto` and `xattr=sa` automatically, and is automatically enabled on systemd-enabled Linux systems
- [ ]  `compression` is enabled by default in ZFS (!) or dropped from the list
- [ ]  `relatime` is enabled by default in ZFS or dropped from the list

I know that's a big ask. But if the install procedures we suggest are *not* the default, there needs to be a strong reason why those are not made upstream, because the end result will be the same: almost everyone will follow those instructions and will have those systems setup that way, regardless of the hardcoded defaults. We'll just make our users lives easier if we upstream those defaults or drop the customization.

In the short term, I think the above command would be more usefully split by regrouping options together more meaningfully, so that tyou'd have this instead:

        zpool create \
            -o ashift=12 \
            -O acltype=posixacl -O xattr=sa -O dnodesize=auto \
            -O compression=zstd \
            -O relatime=on \
            -O canmount=off  -O mountpoint=/ -R /mnt \
            rpool /dev/sdc4

... in other words, the ACL stuff is all on one line, the mount stuff is on its own too, etc. The above, in my mind, is much more readable and something we can already do in the short term.

**Comment by gmelikov** [comment]
> In my mind, OpenZFS should converge to having basically zero custom arguments

Just a side note, that it's a Root on ZFS howto case, so it's expected to be optimized for such usage.

And, unfortunately, some optimal settings are not default because of backward compatibility (for ex. `xattr=sa` restricts pool from RW usage on non-OpenZFS platforms (before ZoL became OpenZFS - on non-Linux platforms).

Second and - we need to support previous defaults, so explicit setting is mandatory for that.

**Comment by ne9z** [comment]
I do not know whether you have taken the time to understand why the various options are chosen: they are, in fact, chosen after many many experiences with Root on ZFS systems, after countless hours of troubleshooting, with various performance requirements, with system rollback capabilities or with machines in production.   The options are there **for a reason**.  They are not there to annoy you.  And, by explicitly specifying important performance-impacting options explicitly -- instead of relying on ZFS defaults, which are often very conservative -- we do not risk having any unknown side-effects in the guide.

I still fail to understand the reason of why should we reduce the number of arguments passed in the guide.  A smaller number for line-count?  I don't think it is wise to just remove them for the sake of removing them.

One could also argue that the very existence of these guides are a complication and should just stick with good-old ext4 instead: `mkfs.ext4 /dev/sda1 && mount /dev/sda1 /mnt && debootstrap bullseye /mnt`

Jokes aside, if you are genuinely interested in the reasoning behind the seemingly over-complicated guides, I suggest you read the excellent introduction written by @djacu , see [here](https://github.com/djacu/nixos-on-zfs/blob/main/blog/2022-03-24.md).

**Comment by djacu** [comment]
I really disagree with the idea of reducing the number of options or changing the defaults.

1. As @gmelikov mentioned, it is for backwards compatibility. If you change the defaults, that will certainly break setup scripts for _everyone else_ that has been using ZFS.
2. If you change the defaults to suit one OS, that might not be the same optimal default for another OS. Invariably, as OS support grows, the minimum common working defaults across all operating systems will shrink. Therefore, I would argue it is best to leave the defaults alone.
3. As @ne9z mentioned, these options were chosen for a reason. I would like someone with more knowledge and experience to tell me which options are most suitable. I think this argument extends to options that are set with values matching the defaults. Let's say in a future timeline where the upstream defaults did change, it would be good to know that the previous default was explicitly set for a reason.

When I read through the NixOS Root on ZFS guide the first time, it was a bit daunting. But after chatting with @ne9z, I realized that a lot of the other guides out there had become stale or had misleading information. So I thought it best to understand everything in the guide as much as possible. The previous link takes you to a file where I try to understand the partition and dataset layouts. If you're interested in the options you can see my write-up [here](https://github.com/djacu/nixos-on-zfs/blob/main/blog/2022-03-10.md). Not everything has a giant discussion on why it was chose; mostly the things I didn't understand.

**Comment by rlaager** [comment]
I applied the `compatibility=grub2` change in commit 
7343c22. I also reworked the dataset creation in commit db5c8c4. See those for more details.

**Comment by pavel-demin** [comment]
Commit [7343c22](https://github.com/openzfs/openzfs-docs/commit/7343c2253f46fdb00ba272a3f4dcf71b5a326e36) breaks instructions for Debian 11 Bullseye. The pool creation command no longer works on a freshly installed and updated system:
```
# zpool create \
    -o cachefile=/etc/zfs/zpool.cache \
    -o ashift=12 -o autotrim=on \
    -o compatibility=grub2 \
    -o feature@livelist=enabled \
    -o feature@zpool_checkpoint=enabled \
    -O acltype=posixacl -O canmount=off -O compression=lz4 \
    -O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
    -O mountpoint=/boot -R /mnt \
    bpool mirror ${DISK1}-part2 ${DISK2}-part2
property 'compatibility' is not a valid pool property

# zpool status 
no pools available
```

**Comment by anarcat** [comment]
> I also reworked the dataset creation in commit [db5c8c4](https://github.com/openzfs/openzfs-docs/commit/db5c8c4785ae125fae144d3c11a644b5be7a6cb4). See those for more details.

this looks great, thanks.

**Comment by anarcat** [comment]
there was one last thing I think we could do here, and i have thrown that idea in #308 as a WIP.

**Comment by anarcat** [comment]
> Commit [7343c22](https://github.com/openzfs/openzfs-docs/commit/7343c2253f46fdb00ba272a3f4dcf71b5a326e36) breaks instructions for Debian 11 Bullseye. The pool creation command no longer works on a freshly installed and updated system:

i took the liberty of filing this as #09.
