### ISSUE TITLE
pool creation command no longer work on Debian 11 Bullseye

### ISSUE THREAD

**Issue by anarcat** [openzfs/openzfs-docs#309]
Commit [7343c22](https://github.com/openzfs/openzfs-docs/commit/7343c2253f46fdb00ba272a3f4dcf71b5a326e36) breaks instructions for Debian 11 Bullseye. The pool creation command no longer works on a freshly installed and updated system:
```
# zpool create \
    -o cachefile=/etc/zfs/zpool.cache \
    -o ashift=12 -o autotrim=on \
    -o compatibility=grub2 \
    -o feature@livelist=enabled \
    -o feature@zpool_checkpoint=enabled \
    -O acltype=posixacl -O canmount=off -O compression=lz4 \
    -O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
    -O mountpoint=/boot -R /mnt \
    bpool mirror ${DISK1}-part2 ${DISK2}-part2
property 'compatibility' is not a valid pool property

# zpool status 
no pools available
```

_Originally posted by @pavel-demin in https://github.com/openzfs/openzfs-docs/issues/307#issuecomment-1133017107_

**Comment by anarcat** [comment]
i wonder if it might be worth working on the bookworm guide now, and have *that* patched in already... what's the support policy here, when do we add newer release and remove old instructions? :)

**Comment by rlaager** [comment]
> i wonder if it might be worth working on the bookworm guide now, and have _that_ patched in already... what's the support policy here, when do we add newer release and remove old instructions? :)

We add new instructions when I get to it, ideally around (a little before or after) the time of the release. If before, I stick a note on that says they're beta instructions. When a new release happens, I stop applying most changes to the old instructions (though I do sometimes apply trivial changes). I used to remove the old instructions, but people like them to stick around for reference for existing systems.

**Comment by anarcat** [comment]
On 2022-05-24 14:58:15, Richard Laager wrote:
>> i wonder if it might be worth working on the bookworm guide now, and have _that_ patched in already... what's the support policy here, when do we add newer release and remove old instructions? :)
>
> We add new instructions when I get to it, ideally around (a little before or after) the time of the release. If before, I stick a note on that says they're beta instructions. When a new release happens, I stop applying most changes to the old instructions (though I do sometimes apply trivial changes). I used to remove the old instructions, but people like them to stick around for reference for existing systems.

That makes sense. Is that policy written down anywhere?

I'd love to see a guide for Debian bookworm. Freeze is coming up in
early 2023, maybe it would make sense to start working on it then...

-- 
A patriot must always be ready to defend his country
against his government.
                        - Edward Abbey

**Comment by rlaager** [comment]
> On 2022-05-24 14:58:15, Richard Laager wrote: > i wonder if it might be worth working on the bookworm guide now, and have _that_ patched in already... what's the support policy here, when do we add newer release and remove old instructions? :) We add new instructions when I get to it, ideally around (a little before or after) the time of the release. If before, I stick a note on that says they're beta instructions. When a new release happens, I stop applying most changes to the old instructions (though I do sometimes apply trivial changes). I used to remove the old instructions, but people like them to stick around for reference for existing systems.
> That makes sense. Is that policy written down anywhere?

Sort of. I did note in the old guides themselves that a newer version is available. I thought that language was stronger than it was. So I just strengthened it in commit f30e459aa21b354f9976d5d2a8bc733e259b5981. I'm open to further suggestions.

**Comment by anarcat** [comment]
> So I just strengthened it in commit https://github.com/openzfs/openzfs-docs/commit/f30e459aa21b354f9976d5d2a8bc733e259b5981. I'm open to further suggestions.

i was actually looking for an explicit policy on that in the [community section](https://openzfs.github.io/openzfs-docs/Project%20and%20Community/index.html), but i guess that's already a good start. :)
