### ISSUE TITLE
Ubuntu Studio iso & ZFS

### ISSUE THREAD

**Issue by spflanze** [openzfs/openzfs-docs#310]
Will these instructions:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2022.04%20Root%20on%20ZFS.html#ubuntu-installer
work just as well with this Ubuntu Studio installation iso:
https://ubuntustudio.org/
?
The only difference I can see are the pre-installed media file editing apps.

**Comment by rlaager** [comment]
I haven't tested, but I'd assume so. However, note that the flavor of the ISO does not affect the flavor of the installed system. The installed system is created using `debootstrap`, so it's a minimal install either way. If you want to get the Ubuntu Studio experience, you should (presumably, I don't use it and haven't tested) install the `ubuntustudio-desktop` package (as opposed to e.g. `ubuntu-desktop`).
