### ISSUE TITLE
Debian Bullseye pinning list not up to date ?

### ISSUE THREAD

**Issue by udf2457** [openzfs/openzfs-docs#314]
The pinning list (at https://github.com/openzfs/openzfs-docs/blob/master/docs/Getting%20Started/Debian/index.rst) does not seem to be up to date ?

If we take https://packages.debian.org/source/bullseye-backports/zfs-linux as the source of truth, then (unless I'm mistaken !) there are the following observations to be made.

Not present in the docs:

- libpam-zfs
- libzfsbootenv1linux
- libzfslinux-dev
- libzpool5linux
- python3-pyzfs
- pyzfs-doc
- spl
- zfs-dracut
- zfs-initramfs

Present in the docs, but not in the repo:

- libnvpair1linux
- libuutil1linux
- libzfs2linux
- libzpool2linux
- zfsutils-linux-dev 

Could someone please double check my observations and update the docs accordingly ?

Perhaps it would be more sensible to use globs ?  e.g. `libzfs* zfs* libzpool*` etc. ?

In addition, since the docs specify the `linux-image-amd64` meta package, surely you should use the `linux-headers-amd64` meta package too ?

**Comment by rlaager** [comment]
I don't see any errors in your reasoning.

Globs are probably reasonable for the libraries, but I wouldn't do something as broad as `zfs*`. That said, it looks like we can just use `Package: src:zfsutils-linux`. So I did that.
