### ISSUE TITLE
ZSys Support

### ISSUE THREAD

**Issue by spflanze** [openzfs/openzfs-docs#315]
The how to at:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2022.04%20Root%20on%20ZFS.html 
states that the it still uses ZSys, but this will probably be removed from it in the future.

For 22.04 installations that used ZSys in the install procedure, if ZSys is removed from Ubuntu in the future, what would that mean for the installation of upgrades to Ubuntu versions that no longer have ZSys? Would an upgrade, to say 24.04, still be automated? Or would a full reinstall be required?

**Comment by rlaager** [comment]
I think that mainly depends on what they do with initramfs stuff. I think (but am not sure) that they patched the initramfs code a bit for the zsys layout. If they did and they remove that, then existing installs would break.
