### ISSUE TITLE
Arch on ZFS: Encrypt Boot Pool cryptomount "issue"

### ISSUE THREAD

**Issue by Reuenthal767** [openzfs/openzfs-docs#316]
First of all thanks for the Archlinux guide.

I was able to make everything work as I desired but I nearly gave up because of the code that can be found here: https://github.com/openzfs/openzfs-docs/blob/master/docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/4-optional-configuration.rst#encrypt-boot-pool

```
tee -a /etc/grub.d/09_bpool_luks2-decryption <<FOE
#!/bin/sh  
cat <<EOF  
  insmod luks2  
  insmod pbkdf2  
  insmod part_gpt  
  insmod gcry_rijndael  
  insmod gcry_sha256  
  insmod cryptodisk  
  cryptomount hd0,gpt2  
EOF
```  

`cryptomount hd0,gpt2` was not working while I had my installation usb plugged in, because **the usb became hdo!**.

So I wasn't being prompted for the decrypt password and I was getting this error:

```
error: no such device: <some_guid>
loading Linux linux ...
error: file `arch/BOOT/default@/vmlinuz-linux` not found.
Loading initial ramdisk ...
error: you need to load the kernel first.
```

Now I don't know if made a mistake, if there is a better way to do it or if it should be obvious, but I think that adding a little warning in the documentation would be great!

**Comment by ne9z** [comment]
Yes, at this time there isn't really a solution besides adding a warning about detaching the bootable media before reboot.

Thanks for spotting the issue!  Will be added in a commit.

**Comment by gmelikov** [comment]
@ne9z is it still actual?

**Comment by ne9z** [comment]
The section mentioned in the issue description was removed and encrypted boot pool is no longer supported.  This issue is not relevant any more.  The user is advised to follow [generic guide](https://wiki.archlinux.org/title/dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_(GRUB)) on Arch Linux wiki.
