### ISSUE TITLE
mkdosfs

### ISSUE THREAD

**Issue by spflanze** [openzfs/openzfs-docs#317]
In Section 4.7 in the document at:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2022.04%20Root%20on%20ZFS.html#step-4-system-configuration

I have some confusion about what is meant by "the additional disks". 

1) My system has 2 x 2TB nvme SSD, and 2 x 12 TB HDD. The Ubuntu OS is to be in the SSDs are to contain the boot pool, root pool, swap pool, LVM write through cache, UEFI boot parrtition, and the Ubuntu MBR partition. The HDD is to contain home pool,where the /home directory is to be. Is  mkdosfs to be done on both the SSD, and HDD?

2) Is this mkdosfs to be done for every partition, or only their part1 partitions? Is mkdosfs to be done only on the UEFI booting partition?

**Comment by rlaager** [comment]
The `mkdosfs` is for the UEFI ESP. So only for the `-part1` partitions, which only need to exist on the disks that are the boot disks. For human sanity, this would normally be the disks that contain the `bpool`, though there's no hard technical requirement on that.

So in your case, the two SSDs should have a partition 1, and you should `mkdosfs` both of those.

I hope that helps. If not, let me know. I believe you can still comment on this issue even if I close it. If not, drop me an email at rlaager@wiktel.com.

**Comment by spflanze** [comment]
Thank you for you response. What you said was my best guess, and so that is what I had already done. Since I now know I did step 4.7 correctly, I known now that what I did at step 4.7 does not account for the boot failure. I will describe that failure in another thread.

**Comment by spflanze** [comment]
I am looking at what I did, and I am looking for mistakes I made.
What is the purpose of the UUID? Should different ones be generated for the SSD, and HDD, mirrored pairs?

**Comment by rlaager** [comment]
The "UUIDs" (which are not really UUIDs) are for zsys (which I'm going to be ripping out of the 22.04 guide at some point, given that Ubuntu has basically abandoned it). I use the same UUID for root and boot; I'm not sure what Ubuntu's installer does.

If I were you, I'd set aside the HDD home pool thing initially. Just do the install as written. Once you have a working system booted normally, then you can worry about attaching the HDDs, creating a pool on them, and then creating datasets to mount at /home. Login as root when moving the home directory for your user.

**Comment by spflanze** [comment]
In your instructions you lz4 compress both bpool, and rpool.

What is the benefit of compressing the rpool? My priorities are the security if encryption first, and performance second. I am not much concerned about efficient storage because I have lots of it. What is the benefit of compressing the root pool (rpool)? Would the additional processor time required to compress a file be less than the additional time it would take to read, and write, the same file? If a bit were flipped in a compressed file, for whatever cause, a cosmic ray maybe, would the risk of data loss be enhanced by compression due to greater difficulty decompressing it, and inspecting it to make corrections?

**Comment by rlaager** [comment]
> What is the benefit of compressing the rpool?

Space savings, and with lz4, increased performance.

> Would the additional processor time required to compress a file be less than the additional time it would take to read, and write, the same file?

With lz4, yes.

> If a bit were flipped in a compressed file, for whatever cause, a cosmic ray maybe, would the risk of data loss be enhanced by compression due to greater difficulty decompressing it, and inspecting it to make corrections?

In theory, yes. But in practice, are you going to be able to do that anyway? Probably not. And if the bit flip is in metadata, it's even less likely. I wouldn't consider "don't use compression" a viable data protection strategy. Use redundancy if possible, and more importantly, have a backup.

**Comment by gmelikov** [comment]
Just a sidenote - lz4 will be enabled by default in next major OpenZFS release.
