### ISSUE TITLE
Debian wiki page - issue with apt preferences

### ISSUE THREAD

**Issue by Piscium** [openzfs/openzfs-docs#318]
There is an issue in this page:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html#

It was introduced in this commit:
https://github.com/openzfs/openzfs-docs/commit/36c1f2f5cdb9e648e8bebe64b18ce27a27826ecb

The issue is that when setting preferences it references a non-existent source package. Currently:
**Package: src:zfsutils-linux**
It should be instead:
**Package: src:zfs-linux**

The commit above did two other similar changes. They need to be fixed too.

**Comment by rlaager** [comment]
Thanks! Sorry about that. That's what happens when I don't test.

**Comment by Piscium** [comment]
Thanks
