### ISSUE TITLE
Ubuntu 20.04 Root on ZFS Giude - Mounting boot when rescuing using a live cd

### ISSUE THREAD

**Issue by lciti** [openzfs/openzfs-docs#32]
In the Guide ["Ubuntu 20.04 Root on ZFS", section "Rescuing using a Live CD" ](https://github.com/openzfs/openzfs-docs/blob/ddc56b0106f5fb7b89c71516328c33a296d9ee56/docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.rst#rescuing-using-a-live-cd), mounting boot in the chrooted environment gives an error (because boot is not found in fstab). I think that way of mounting boot is a leftover from the 18.04 guide. I was able to fix the issue by mounting boot outside the chrooted environment (in the same way as root is mounted). I.e.:

        @@ -1180,25 +1180,25 @@
         Mount everything correctly::
         
           zpool export -a
           zpool import -N -R /mnt rpool
           zpool import -N -R /mnt bpool
           zfs load-key -a
           # Replace “UUID” as appropriate; use zfs list to find it:
           zfs mount rpool/ROOT/ubuntu_UUID
        +  zfs mount bpool/BOOT/ubuntu_UUID
           zfs mount -a
         
         If needed, you can chroot into your installed environment::
         
           mount --rbind /dev  /mnt/dev
           mount --rbind /proc /mnt/proc
           mount --rbind /sys  /mnt/sys
           chroot /mnt /bin/bash --login
        -  mount /boot
           mount -a

**Comment by rlaager** [comment]
Thanks!
