### ISSUE TITLE
Prefer linux-headers meta package on Debian

### ISSUE THREAD

**Issue by gbonfiglio** [openzfs/openzfs-docs#327]
The page at https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html includes this line:

```
apt install dpkg-dev linux-headers-$(uname -r) linux-image-amd64
```

`linux-headers-$(uname -r)` is resolved into installing the linux-headers package for the current kernel only - after a kernel upgrade, zfs module will fail to build and loading at boot will subsequently fail with:

```
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.10.0-16-amd64
```

Is there a specific reason why the specific package is installed instead of the related `linux-headers-amd64` meta package, which means every future kernel update will also come with the correct `-headers`?

**Comment by gmelikov** [comment]
Even better - since bullseye there is `generic` virtual package
