### ISSUE TITLE
NixOS getting started - no mention of mkswap

### ISSUE THREAD

**Issue by senorsmile** [openzfs/openzfs-docs#343]
I used the guide to redo a NixOS installation using ZFS on root.  Everything mostly went well, but I realized that the swap partition that was created didn't actually get picked up and put into the hardware config.  This is because `mkswap` is never run.  

Since the option is given for turning encryption on for the root container, would it be appropriate to also add the current recommended way to encrypt the swap partition?  From what I can tell, the recommended way is still use luks with swap on its own partition rather than using a zpool, correct?

**Comment by ne9z** [comment]
There is no need to use mkswap if randomEncryption is used, see [this page](https://github.com/openzfs/openzfs-docs/blob/5777295f0aae9e7f585d45f4667b7a6ad21d69e5/docs/Getting%20Started/NixOS/Root%20on%20ZFS/2-system-configuration.rst) and search for "If swap is enabled:" in that page.

```nix
# in hardware-configuration.nix
{
  swapDevices = [
    {
      device = "/dev/disk/by-id/${diskName}-part4";
      discardPolicy = "both";
      randomEncryption = {
        enable = true;
        #enable trim on SSD, has security implications
        allowDiscards = true;
      };
    }
  ];
}
```

It's most likely left out during the extensive cleanup effort : #330.  Will be added back later.

**Comment by victornoel** [comment]
Hey, just wanted to note here that the same happened for Archlinux, the instructions about the swap were lost too. I can create another ticket if needed.

**Comment by ne9z** [comment]
Hello.  This issue is now fixed in NixOS guide.  https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Root%20on%20ZFS/1-preparation.html

For Arch Linux, please open a separate issue.

**Comment by senorsmile** [comment]
lgtm.  

btw, you linked the Arch guide but meant to link to the NixOS guide: https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS/2-system-installation.html.
