### ISSUE TITLE
On some configurations, zfs-import-bpool.service fails

### ISSUE THREAD

**Issue by alb-i** [openzfs/openzfs-docs#349]
The command
```zpool import -N[...]```
in the zfs-import-bpool.service script fails, indicating that the pool is not found. This can be fixed by adding the boot pool partition device as parameter to the import command.

**Comment by rlaager** [comment]
If anyone stumbles across this issue, I would love to know more about your setup, so we can try to figure out what is causing this.

**Comment by sney** [comment]
I have stumbled across this issue, with the exact same symptoms and exact same fix. I followed these instructions basically to the letter: https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html , so it was installed as debian bullseye with linux 5.10.0-18-amd64 (5.10.140-1) and zfs 2.0.3-9. The issue also persisted with linux 5.18.16-1 and zfs 2.1.5-1 from bullseye-backports. 
The boot and root pools are both on a single samsung nvme and the hardware is a new amd ryzen desktop. 
lshw-short: https://termbin.com/xnhvj
Please let me know if you want any more info.
