### ISSUE TITLE
Can't boot if single drive missing with mirrored pools

### ISSUE THREAD

**Issue by nasamaher** [openzfs/openzfs-docs#371]
Hi,

A mirrored install should allow for booting even if one of the drives is offline, right?

I've tried installing multiple times (without errors) on mirrored 4GB SSDs using UEFI and get the same results.  Both drives must be online.  If one drive is disconnected I have a problem.

lsblk output after the install:
![image](https://user-images.githubusercontent.com/1706941/209701187-c6a3f476-d60e-4161-84cd-cd15f69db809.png)

If I remove /dev/sda, then I get the Grub menu, but upon trying to load the OS I get

_"Unknown device 0.  You need to load the kernel first"_

If I remove /dev/sdb, then on boot, no Grub menu; I get dropped to Grub Shell (without an apparent warning message)

I've gotten the same result twice.  I should note in both installs I also was faced with not being able to import rpool, but I see this is a common issue and I resolved it in the initramfs shell.

**Comment by prehonor** [comment]
installing the boot loader...
setting up /etc...
/etc/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
updating GRUB 2 menu...
installing the GRUB 2 boot loader on /dev/disk/by-id/ata-WDC_WD10EZEX-08WN4A0_WD-WCC6Y5YF14H1...
Installing for i386-pc platform.
Installation finished. No error reported.
installing the GRUB 2 EFI boot loader into /dev/disk/by-id/ata-WDC_WD10EZEX-08WN4A0_WD-WCC6Y5YF14H1-part1...
Installing for x86_64-efi platform.
/nix/store/plikx1pi79sf46hbwz73416bd9865lwi-grub-2.06/sbin/grub-install: error: failed to get canonical path of `devtmpfs'.
/nix/store/cxzmkzazap2337gx1dfb6mk3kmdhrj2c-install-grub.pl: installation of GRUB EFI into /dev/disk/by-id/ata-WDC_WD10EZEX-08WN4A0_WD-WCC6Y5YF14H1-part1 failed: No such file or directory

It failed again,saddly

**Comment by gmelikov** [comment]
@ne9z wasn't it fixed by https://github.com/openzfs/openzfs-docs/pull/384 ?

**Comment by ne9z** [comment]
This issue was filed in December 2022, and yesterday, another person
commented on this issue for a totally unrelated problem.  I do not
understand their motivation of doing this.

Now, the pull request you mentioned, fixes the problem from yesterday.

Regarding the situation where mirrored pools fails to boot when one disk
fails/is missing,  I do not have enough free time to investigate the
matter further at the moment, so we can leave the issue open for now.

**Comment by ne9z** [comment]
@nasamaher Hello. With the new guide I was able to boot a two-disk mirrored system with one disk removed.  Also, instructions for replacing the faulty disk has been added.  Please report back if you still can not boot a mirrored system.  Thanks.

https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS/1-preparation.html

**Comment by nasamaher** [comment]
@ne9z thanks for reporting this.  I ended up doing a standard Ubuntu 20 install (with ZFS option) and then followed [these instruction](https://gist.github.com/yorickdowne/a2a330873b16ebf288d74e87d35bff3e) so I'm not working on this anymore.  I will certainly retry if the opportunity presents itself.  Given this and your success, I will close with this comment.

Interesting sidebar: after doing the above I upgraded to Ubuntu 22 and I lost the boot with missing disk ability!  I ended up repeating the above and staying on Ubuntu 20 (which is fine for us).

Steve

**Comment by ne9z** [comment]
I would still recommend giving the NixOS guide a try -- whether
mirrored, raidz123 or single disk -- on a spare computer, just to have
an idea of how easy the administration of a NixOS system is, thanks to
its declarative, purely functional approach to configuration and package
management.

Obviously I'm biased, but yesterday I was able to complete a mirrored
installation under 8 minutes :-) boot computer with live media, set up SSH
access, copy-paste instructions, apply configuration & install system,
then reboot to new system.
