### ISSUE TITLE
Module parameter zfs_dirty_data_max_max does not mention 4GiB limit

### ISSUE THREAD

**Issue by edgarsuit** [openzfs/openzfs-docs#375]
The documentation for the `zfs_dirty_data_max_max` module parameter indicates that the default value is 25% of physical RAM: https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#zfs-dirty-data-max-max

In the code, `zfs_dirty_data_max_max` is actually set to MIN(25% of system RAM, 4GiB): https://github.com/openzfs/zfs/blob/289f7e6adb58336281e87bffe853b280fc8ee498/module/zfs/arc.c#L8091

Assuming this 4GiB limit for `zfs_dirty_data_max_max` is intended, the documentation should be updated to reflect this. The man page for ZFS(4) should also be updated.

I'll also note that the `zfs_dirty_data_max` documentation should probably indicate that the default is MIN(10% of system RAM, zfs_dirty_data_max_max).

**Comment by gmelikov** [comment]
Fixed in https://github.com/openzfs/openzfs-docs/commit/48e3fded3d770f7b9d27e9281f934433b7d533b8
