### ISSUE TITLE
Table formatting in "ZIO Schedulers.rst"

### ISSUE THREAD

**Issue by ahrens** [openzfs/openzfs-docs#39]
Due to line-wrapping in the raw table code, spaces are inserted inside of the tunable names, which should each be considered a single, unbreakable word.  We might also want to format the tunable names as `code`.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/799124/88559377-986b9500-cfe1-11ea-8b7b-7dbeb7f175cf.png">

Side note: what tool do folks use to edit the ASCII-art tables?

**Comment by gmelikov** [comment]
Thanks for finding! I'll rework this table after my vacation.

Unfortunately, IMHO table formatting is a weak point of rst, I didn't find briefly any good editor for that. One thing I've found that it can render usual csv-like table. Will look at this later again.
