### ISSUE TITLE
NixOS: DNS doesn't work if NetworkManager is not enabled

### ISSUE THREAD

**Issue by mariaa144** [openzfs/openzfs-docs#415]
When I installed my system without NetworkManager enabled as is default with the guide, my system wasn't able to get DNS. I wasn't able to easily remedy the situation because I couldn't just enable NetworkManager. The packages were missing and couldn't be downloaded. `nixos-rebuild` couldn't find the servers it needed because of no DNS. I ended up reinstalled with NetworkManager enabled.

Should DNS work by default if NetworkManager is disabled?

**Comment by ne9z** [comment]
Yes it should.

Either you are using DHCP where it should "just work".

Or you are using a wireless network, in that case you need to configure
the built-in DNS client, systemd-resolved.

In any case, you can override the DNS server configuration by directly
replacing the contents of /etc/resolv.conf.  An example would be the
following:

cat  /etc/resolv.conf
nameserver 1.1.1.1

which sends all resolution requests to CloudFlare server.

**Comment by ne9z** [comment]
> I think so, too, that this is out of scope for the zfs guide.

NetworkManager is already removed.
