### ISSUE TITLE
Failed Installation (override with `zpool create -f`, uninitialized /etc, missing UEFI entry,  more than one matching pool)

### ISSUE THREAD

**Issue by manuel-plavsic** [openzfs/openzfs-docs#428]
I successfully installed NixOS+ZFS following the old guide in the past, I think I am doing something wrong now. As I cannot say if these issues are related or not, and they happened multiple times together, I am opening an issue here.

I tries reinstalling NixOS+ZFS multiple times without success in the last hours.

These issues presented sometimes together, sometimes not together:

- `zpool create` needs `-f` to be invoked correctly, as the partition potentially exists.
  - System Installation - step 3 (and one time also in step 4)
  - I noticed this sometimes disappears if I run `wipefs -a /dev/sdX` before I use the installation guide. I also deleted the partitions with gParted and created a new table. However, i don't know why, but this doesn't seem always to work correctly.

- `unitialized /etc detected` 
  - System Configuration - step 8
  - I only noticed this the last time I tried installing NixOS.
  
![Screenshot_20230419_131308](https://user-images.githubusercontent.com/55398763/233103598-2059080c-1340-4ab0-b28c-4a0b46a691b2.png)
    - NB: `world` is a slight modification to `exampleHost`, as I didn't like the host name. The code is here https://gitlab.com/mplavsic/nixos-installation/-/blob/main/hosts/world/default.nix
  
- There is no UEFI entry after installation. On the other hand, the GUI NixOS installer successfully finishes with a UEFI entry (something like `Linux Configuration`).
  - In my UEFI settings I did not enable a feature that prevents new UEFI entries
  - This means that NixOS is started in fallback mode 

- When starting NixOS, it waits for a long time (before the prompt to enter my FDE password (native encryption)).
  - Actually, this prompt never gets display, as the system crashes (kernel panic)
  - Cannot import 'rpool' (or maybe it was 'bpool'), more than one matching pool

![IMG_20230419_105312_198](https://user-images.githubusercontent.com/55398763/233105586-0a664ad3-dc87-46b5-b7b3-52ee34187364.jpg)

**Comment by ne9z** [comment]
> unitialized /etc detected

This is normal and can be ignored.

> `world` hostname

It's fine.

**Comment by manuel-plavsic** [comment]
Thank you a lot for your prompt replies. I will try again soon and I'll close if it works correctly.

Just a question: why is `removableEfi = true;` the default?

**Comment by ne9z** [comment]
It is well-known that some motherboards have faulty implementations of
UEFI standard and have some bizaare bugs such as refusing to boot
anything other than the fallback or an entry named "Windows Boot
Manager".  You can see here for details:

  https://mjg59.dreamwidth.org/20187.html
  https://www.rodsbooks.com/efi-bootloaders/installation.html

> Lenovo once shipped products with a known bug that causes the system
> to refuse to boot unless the boot loader's name (NewLoader in this
> example) is either Windows Boot Manager or Red Hat Enterprise Linux.

As the author of the guide, it is more important for me to make the
computer **boot** than adding some custom entries in NVRAM.  Therefore
removableEfi is by default enabled.

**Comment by manuel-plavsic** [comment]
I used `blkdiscard` this time.

I tried running `zpool export -a` (last step), but the pool was busy.

![2023-04-19 18 00 00](https://user-images.githubusercontent.com/55398763/233134432-bc4e86fc-4fd9-454d-a880-3c73dbd30434.jpg)

I rebooted without exporting. This is is the output I get on startup:

![2023-04-19 18 00 06](https://user-images.githubusercontent.com/55398763/233134690-35ecd5a5-c4af-4463-8482-b34e4a47a085.jpg)

![2023-04-19 18 00 11](https://user-images.githubusercontent.com/55398763/233134707-2041b911-672e-4c4a-96af-6f295565f097.jpg)

Do you think that the failed `zpool export -a` was the issue? If so, should I run it again with `-f`? Or is the issue likely something else?

**Comment by ne9z** [comment]
manuel-plavsic ***@***.***> writes:

> I used `blkdiscard` this time.
> I tried running `zpool export -a` (last step), but the pool was busy.
> I rebooted without exporting. This is is the output I get on startup:
> Do you think that the failed `zpool export -a` was the issue?

Yes.  The failed reboot is resulted from the failed export.

> If so, should I run it again with `-f`? Or is the issue likely something else?

You need to leave the pool before exporting it.  In your screenshot, you
are inside the pool when trying to export it:

> ***@***.***:/tmp/tmp.mountpoint/etc/nixos]  zpool export -a`
> `cannot export 'rpool': pool is busy`

Next time, try change the current working directory back to your home
before exporting it:

**Comment by ne9z** [comment]
GitHub is just plain bad at email.  Let me repost it:

  > I used `blkdiscard` this time.
  > I tried running `zpool export -a` (last step), but the pool was busy.
  > I rebooted without exporting. This is is the output I get on startup:
  > Do you think that the failed `zpool export -a` was the issue?

  Yes.  The failed reboot is resulted from the failed export.

  > If so, should I run it again with `-f`? Or is the issue likely something else?

  You need to leave the pool before exporting it.  In your screenshot, you
  are inside the pool when trying to export it:

  ```sh
  [root@nixos:/tmp/tmp.mountpoint/etc/nixos]  zpool export -a
  cannot export 'rpool': pool is busy
  ```

  Next time, try change the current working directory back to your home
  before exporting it:

  ```sh
  [root@nixos:/tmp/tmp.mountpoint/etc/nixos]  cd ~
  [root@nixos:~]  zpool export -a
  ```

**Comment by ne9z** [comment]
You might also need to unmount the filesystem again:
```sh
[root@nixos:/tmp/tmp.mountpoint/etc/nixos]  cd ~
[root@nixos:~] umount -Rl "${MNT}"
[root@nixos:~]  zpool export -a
```

The umount command will not execute properly if you are still inside the filesystem that you want to unmount.

**Comment by ne9z** [comment]
Reminder.  Any customization not mentioned in the guide is unsupported.  You must do your customization after reboot.

In this instance, you
- tried to use your own config repo
- tried to customize before reboot
- forgot to leave the pool (due to customization) before export

You must do your customization **after reboot**, not before.

I do not have time to support every config that the user created for themselves.  Also see #413, where the user did not follow the guide during installation, and asked me to troubleshoot their own customization.  Sorry but I don't have the time.

**Comment by manuel-plavsic** [comment]
Everything worked. Thank you a lot.

This is a totally valid point.
