### ISSUE TITLE
Base urls in /etc/yum.repos.d/yum.repos.d return 403 forbidden

### ISSUE THREAD

**Issue by maxkremer** [openzfs/openzfs-docs#429]
### Steps to reproduce

I did this on amazon linux 2 which is based on rhel7 so I followed the instructions in the docs to download and install zfs on el7.

`sudo yum install https://zfsonlinux.org/epel/zfs-release-2-2.el7.noarch.rpm`

The above will create `zfs.repo` in `/etc/yumrepos.d` that looks like this:
```
[zfs]
name=ZFS on Linux for EL$releasever - dkms
baseurl=http://download.zfsonlinux.org/epel/$releasever/$basearch/
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs

[zfs-kmod]
name=ZFS on Linux for EL$releasever - kmod
baseurl=http://download.zfsonlinux.org/epel/$releasever/kmod/$basearch/
enabled=0
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs

[zfs-source]
name=ZFS on Linux for EL$releasever - Source
baseurl=http://download.zfsonlinux.org/epel/$releasever/SRPMS/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs

[zfs-testing]
name=ZFS on Linux for EL$releasever - dkms - Testing
baseurl=http://download.zfsonlinux.org/epel-testing/$releasever/$basearch/
enabled=0
metadata_expire=7d
gpgcheck=1
```
Attempt any one of the following yum installs 

```
yum install -y epel-release
yum install -y kernel-devel
yum install -y zfs
```
You will get an error with the message:
```
failure: repodata/repomd.xml from zfs: [Errno 256] No more mirrors to try.
http://download.zfsonlinux.org/epel/2/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden
```

**Comment by gmelikov** [comment]
@tonyhutter could you please look at this issue?

**Comment by tonyhutter** [comment]
> `http://download.zfsonlinux.org/epel/2/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden`

Even though Amazon Linux 2 is based on RHEL 7, it's reporting a $releasever of 2 instead of 7.  That's explains the 2 in the URL and why it's not working.

You could try hardcoding 7 in place of `$releasever` in your `/etc/yum.repos.d/zfs.repo` and it might work.

**Comment by ne9z** [comment]
You need to install the kernel-headers package, as indicated by the
output of yum command:

 Loading new zfs-2.0.7 DKMS files...
 Building for 5.10.167-147.601.amzn2.x86_64
 Module build for kernel 5.10.167-147.601.amzn2.x86_64 was skipped since the
 kernel headers for this kernel does not seem to be installed.

Install that, then reinstall zfs package.  Modules should then be built properly.

**Comment by tonyhutter** [comment]
> You need to install the kernel-headers package, as indicated by the output of yum command:

And if that doesn't work for you, you could also try disabling the 'zfs' repo and enable the 'zfs-testing' repo in /etc/yum.repos.d/zfs.repo.  'zfs-testing' will give you the newest zfs-2.1.11, which may be more compatible with Amazon's kernel.

**Comment by maxkremer** [comment]
my bad - i did a yum update and rebooted and everything works fine, successfully created a zfs pool on 2 ebs volumes. Thanks for the support.
