### ISSUE TITLE
misssing man pages when contributing to Debian xxx Root on ZFS

### ISSUE THREAD

**Issue by jim-perkins** [openzfs/openzfs-docs#443]
when following the directions at :
https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html#contributing

I get a couple warning when running 'make html'
/home/user/path/openzfs-docs/docs/_TableOfContents.rst:1: WARNING: toctree contains reference to nonexisting document 'man/index'

I see the public pages have the man pages so maybe a step is missing in the contribution section?  Or maybe it doesnt matter at all.

**Comment by gmelikov** [comment]
It doesn't matter unless you contribute to man pages generator, so expected. Man pages generation will slow build process without necessity for you.

**Comment by rlaager** [comment]
@jim-perkins I'm not against a PR to make a note of this.
