### ISSUE TITLE
Could we keep versioned instances of the man pages at least around?

### ISSUE THREAD

**Issue by rincebrain** [openzfs/openzfs-docs#447]
Sometimes we do things like delete fields or parameters in newer releases, and it's sometimes useful to point people to those without having to dig through git history.

(This specifically came to mind when reading openzfs/zfs#15052 and thinking "we should maybe keep the references to explain the old fields around" and then going "no keeping old versions of the docs for each release series is probably a better solution")

**Comment by gmelikov** [comment]
Done 
![image](https://github.com/openzfs/openzfs-docs/assets/3868786/0e76aed0-3e14-4e6b-8388-bac87bd9f441)
