### ISSUE TITLE
How to sponsor the project/say thank you?

### ISSUE THREAD

**Issue by gigatexal** [openzfs/openzfs-docs#455]
Hi folks.

I know lots of large companies and institutions use ZFS (the oxide computer folks building really cool bespoke racks of servers with super fast SSDs, and Lawrence Livermore does and Oracle etc etc) but I don't know if there's funds to kick a thank you to all the devs and volunteers that work to make this such an awesome project. 

So I was curious if there's a Github Sponsors or a foundation or some other cause to donate to on a monthly basis because ZFS is so vital to my workflow and how I secure my data that I hope to see the project and those that spend time on it know they're seen, thanked, and maybe even earn a few bucks and ensure it stays around for many many years to come [1].

Thanks!

[1] My measly donation alone won't ensure the livelihood of the project but I hope others will join me. I think more and more folks using open source tech, if they are able, should give back to the projects and devs that work on those projects be it in the form of time or in my case, money.

**Comment by gmelikov** [comment]
There is a section about donation on https://openzfs.org/wiki/Main_Page 

maybe @ahrens can pinpoint something more on this topic, IIRC it's not the first issue about sponsorship.

**Comment by ahrens** [comment]
@gigatexal Thanks for your kind words and support!  As @gmelikov mentioned, you can donate to the project via the link on [our webpage](https://openzfs.org/wiki/Main_Page#Donate).  This is a tax-deductable donation via SPI, which is an umbrella foundation that manages our finances.  You can make a one-time donation or set up a recurring donation.  Funds are used to cover our expenses, e.g. hosting, domain names; and as a backstop for conference expenses (which are mostly covered by corporate sponsorships and ticket sales; see the upcoming [OpenZFS Developer Summit](https://openzfs.org/wiki/OpenZFS_Developer_Summit)).

We don't have a mechanism to give money to individual contributors / leaders of the project.

**Comment by gigatexal** [comment]
```
Thanks for setting up a monthly donation of $10.00 USD to
Software in the Public Interest, Inc.
```
thanks!
