### ISSUE TITLE
Document remote unlock for Debian Buster Root on ZFS

### ISSUE THREAD

**Issue by khimaros** [openzfs/openzfs-docs#46]
Debian Buster and later should support ZFS decrypt via dropbear-initramfs. This would be helpful to document in the Root on ZFS instructions, as remote unlock is particularly relevant for that use case.

Doc: https://github.com/openzfs/openzfs-docs/blob/master/docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.rst

I'm interested particularly in native ZFS encryption. There is already [some documentation](https://hamy.io/post/0009/how-to-install-luks-encrypted-ubuntu-18.04.x-server-and-enable-remote-unlocking/) for doing this with LUKS keys.

**Comment by rlaager** [comment]
This only works with https://github.com/openzfs/zfs/commit/1cc635a2dd0379181950a1458255ea8ae8b9c1e0 (and if you're trying to build it, the couple refactor commits from me before that) from https://github.com/openzfs/zfs/pull/10027 and the follow-up https://github.com/openzfs/zfs/commit/7fcf82451c4b75afe327c77683f66bf0c6396a48 from https://github.com/openzfs/zfs/pull/10307. These have not landed in a (non-rc) release yet. They are in 2.0.0-rc1 and will be in the final 2.0.0. If/when that lands in buster-backports, then this can be added to the instructions.

**Comment by tehnic-take3** [comment]
Hello,

for Debian Buster i use this "ugly" workaround.

Install and configure dropbear-initramfs.
After reboot log in your box with ssh and execute the following:

`~ # ps`

note PID1 of "plymouth ask-for-password --prompt Encrypted ZFS password for rpool"
note PID2 of "/sbin/zfs load-key rpool"

`~ # echo "<passphrase>" >/proc/<PID2>/fd/0`
`~ # kill <PID1>`

Best regards, Robert

**Comment by rlaager** [comment]
@tehnic-take3 That's a nice hack! I'm not going to add that to a guide, but it's definitely clever. :)

**Comment by rlaager** [comment]
Current status: OpenZFS 2.0.0 has been released, but is not yet packaged for Debian. So we are waiting for 2.0.0 to land in unstable, then migrate to testing, then (hopefully) be backported to buster-backports. At that time, I'll have to review and update the guide.

**Comment by khimaros** [comment]
thank you for the update, i'm excited to see that this has been progressing!

**Comment by rlaager** [comment]
Update: OpenZFS 2.0 was uploaded to Debian experimental.

**Comment by rlaager** [comment]
Update OpenZFS 2.0 was uploaded to Debian unstable. Barring major problems, it should migrate to testing in a week. At that point, it will be _eligible_ for backporting. I assume the maintainers will backport it, but that's not guaranteed, nor is there a particular timeline. If/when that happens, I plan to review/update the guide, and this is something that I should be able to address at the same time.

**Comment by n0rc** [comment]
ZFS 2.0 is in backports for some time now and is working flawlessly for me.

**Comment by anarcat** [comment]
> ZFS 2.0 is in backports for some time now and is working flawlessly for me.

that's great, but how do you actually do remote unlock in ZFS with this?

**Comment by n0rc** [comment]
> that's great, but how do you actually do remote unlock in ZFS with this?

With [zfsunlock](https://github.com/openzfs/zfs/blob/master/contrib/initramfs/zfsunlock) from zfs-initramfs.

**Comment by anarcat** [comment]
but concretely, what's the procedure? dropbear-initramfs depends on cryptsetup, so I assume that's not it?

**Comment by rlaager** [comment]
I obviously haven't gotten to this, but it seems like I should include this when I eventually get to updating for Debian Bullseye.

**Comment by anarcat** [comment]
too bad that systemd-cryptsetup doesn't support zfs. :)

**Comment by kayg04** [comment]
Hello, sorry for asking this in the old post but can I make `zfsunlock` ask for password for multiple pools instead of one? I am talking about Debian Bookworm.
