### ISSUE TITLE
openZFS update from Nov. 22/24 may have cause problem with external volume?

### ISSUE THREAD

**Issue by FPAinGHUB** [openzfs/openzfs-docs#476]
On Nov 24 my system installed updates (please see attached) and 'linux ZFS' was one of them. After that, it has not been possible to connect an android phone via USB cable to my system. This same problem occurred to another PC of ours, similar system. They all have latest updates that come through to Linux Mint installs.

I wonder if the ZFS update package is the culprit. Help is much appreciated. Thanks in advance.
![updatesLedProblemAndroid2](https://github.com/openzfs/openzfs-docs/assets/78050584/f04ce001-1ba5-47ae-8e0e-331edb80a7a9)

**Comment by gmelikov** [comment]
ZFS is not related to usb connections, you may start to bisect with more related packages.
