### ISSUE TITLE
docs/Getting Started/RHEL-based distro/Root on ZFS.rst appears to be completely wrong

### ISSUE THREAD

**Issue by bish0polis** [openzfs/openzfs-docs#495]
docs/Getting Started/RHEL-based distro/Root on ZFS.rst refers to 
- apk
- setup-interfaces
- setup-ntp
- busybox
- setup-apkrepos
- setup-devd

.. and more.  It really looks like someone just copied an Alpine setup as a process to also set up zfs on Rocky/EL hosts.

Can we have this reviewed by someone with experience in the process?

**Comment by gmelikov** [comment]
Could you be more specific about exact problem with guide? Alpine linux is actually used here as live-cd to prepare zfs pool and install minimal RHEL on it. I don't know about actual problems, so will close this issue until further info, thank you.

**Comment by bish0polis** [comment]
I appreciate the spirited and exhaustive discussion.
