### ISSUE TITLE
More adaptive ARC eviction - No information about deprecation of module parameters 

### ISSUE THREAD

**Issue by krzotr** [openzfs/openzfs-docs#513]
Hello,

At the moment I use *zfs 2.2.4*. Merge request [#14359](https://github.com/openzfs/zfs/pull/14359) removed `zfs_arc_meta_*` parameters and added `zfs_arc_meta_balance`.

In [Module Parameters](https://github.com/openzfs/openzfs-docs/blob/f6b91541d925d537e63bac485068194bbcc3c8b9/docs/Performance%20and%20Tuning/Module%20Parameters.rst) documentation page there is no information about depreciation of `zfs_arc_meta_` parameters. There is no information about `zfs_arc_meta_balance`. if I am not wrong versions affected v2.2 and later.

You can find `Man Pages` -> `v2.2` -> `Devices and Special Files` -> `zfs.4` / `man zfs.4`

**Comment by gmelikov** [comment]
Thank you, but it's a duplicate, I'll close it in favor of https://github.com/openzfs/openzfs-docs/issues/491
