### ISSUE TITLE
Ubiquity installer section

### ISSUE THREAD

**Issue by Sithuk** [openzfs/openzfs-docs#52]
Ubuntu installer section:
1. I recommend you clarify that there is a minimum password length for the zfs password. Otherwise Ubiquity crashes.
2. I had to add an extra sudo for the encrypted swap section.
curl https://launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch | \
    sed "s|/etc|/lib|;s|\.in$||" | (cd / ; **sudo** patch -p1)

**Comment by rlaager** [comment]
1. What is the minimum password length?
2. Fixed in 5523d6cb6bb840347156817d984ce410c83dbff3. Thanks!

**Comment by Sithuk** [comment]
The zfsonlinux manpage gives the minimum passphrase length as 8 bytes (so minimum 8 characters): (search for keyword "passphrases")
https://zfsonlinux.org/manpages/0.8.1/man8/zfs.8.html

The Oracle online ZFS guide gives the same minimum 8 character length.
https://docs.oracle.com/cd/E53394_01/html/E54801/gkkih.html

I'd need to test the Ubuntu implementation to confirm for certain.

**Comment by rlaager** [comment]
I added a note in 28ccb936b3cc14fbb9ffd34665f6d43efe859660.
