### ISSUE TITLE
Arch Docs apparently written for alpine

### ISSUE THREAD

**Issue by dhelgerson** [openzfs/openzfs-docs#523]
hi, this is a very strange problem. it seems that the arch on zfs root guide is actually just a copy of the guide for alpine. most notably, the use of apk instead of pacman.

**Comment by gmelikov** [comment]
Arch guide uses alpine live image to install arch after initial boot. There may be other ways, but it's a question of new contributions.

I'll close this issue, feel free to open new one if you have actual problems with guide, thank you.
