### ISSUE TITLE
Increase Debian ZFS Native Encryption Installation Passphrase Tries

### ISSUE THREAD

**Issue by denppa** [openzfs/openzfs-docs#525]
If a Debian system was installed using the ZFS native encryption, initramfs upon boot will only allow 2 passphrase attempts before exiting the prompt. Requiring the user to manually import the pools and unlock them again, or a reboot. Is there a way to increase the attempts to be unlimited, so initramfs does not exit the user from the prompt?

**Comment by gmelikov** [comment]
Not sure that it's capped by X tries https://github.com/openzfs/zfs/blob/master/contrib/initramfs/zfsunlock#L21

IIRC it may be capped with max time for input, but it's the same area to dig - initramfs tools.

I'll close this issue as not a bug, but feel free to add any new info you've found here for future use.

**Comment by denppa** [comment]
Got it, closing issue for now.
