### ISSUE TITLE
Ubuntu 20.04 Root on ZFS guide fails into grub prompt

### ISSUE THREAD

**Issue by Shellcat-Zero** [openzfs/openzfs-docs#57]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04 LTS
Linux Kernel	| 5.4.0-42-generic
Architecture	| x86_64
ZFS Version	| 0.8.3-1ubuntu12.1 
SPL Version	| 0.8.3-1ubuntu12.1 

After following the [Ubuntu 20.04 Root on ZFS](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html) guide for LUKS, single-disk, without any swap, and BIOS-booting, every result boots into a grub rescue prompt where nothing can be read in the boot pool. I initially tried this for UEFI which had the same result, then repeated the procedure for BIOS 3 more times to try to fix the issue or address any missed instructions.

I will likely try the instructions next from 18.04 which uses the bpool service to see if this remedies the issue 20.04.  Any help is much appreciated.

Here is what I see in the grub prompt:
```bash
grub> ls
(hd0) (hd0,gpt5) (hd0,gpt4) (hd0,gpt3) (hd0,gpt1)
grub> ls (hd0,gpt5)/
error: unknown filesystem.
grub> (hd0,gpt4)/
error: unknown filesystem
grub> ls (hd0,gpt3)/
@/ BOOT/
grub> ls (hd0,gpt3)/BOOT/
@/ ubuntu_uLmhPo/
grub> ls (hd0,gpt3)/BOOT/ubuntu_uLmhPo/
@/
grub> ls (hd0,gpt3)/BOOT/ubuntu_uLmhPo/@/
error: compression algorithm 78 not supported
(messaged repeated 2 more times)
error: compression algorithm 103 not supported
(message repeated 3 more times)
grub> ls (hd0,gpt1)/
grub/
grub> ls (hd0,gpt1)/grub/
i386-pc/ fonts/ grub.cfg grubenv unicode.pf2 gfxblacklist.txt
```

**Comment by Shellcat-Zero** [comment]
I have determined that one of the bpool features is incompatible (with grub?), causing the failure.  The offending feature is `feature@zpool_checkpoint=enabled`.  The new bpool then that results in success is:

```bash
zpool create \
    -o ashift=12 -d \
    -o feature@async_destroy=enabled \
    -o feature@bookmarks=enabled \
    -o feature@embedded_data=enabled \
    -o feature@empty_bpobj=enabled \
    -o feature@enabled_txg=enabled \
    -o feature@extensible_dataset=enabled \
    -o feature@filesystem_limits=enabled \
    -o feature@hole_birth=enabled \
    -o feature@large_blocks=enabled \
    -o feature@lz4_compress=enabled \
    -o feature@spacemap_histogram=enabled \
    -O acltype=posixacl -O canmount=off -O compression=lz4 \
    -O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
    -O mountpoint=/boot -R /mnt \
    bpool ${DISK}-part3
```
Upon boot, an error message presents saying "Invalid partition table!" which requires a keypress to proceed.  I am told this is due to the legacy (BIOS) boot, which sees the GPT partition scheme as invalid.  Ideally, I would like the boot process to be non-interactive, going directly to grub and booting the default options.  Is there some way to accomplish that?

**Comment by Shellcat-Zero** [comment]
I was able to fairly easily convert the install to UEFI, eliminating the error message and streamlining the boot process to be fully non-interactive.  

Thanks @rlaager for all your work on the docs.  I was also wondering if perhaps you felt that introducing swap on a zvol with `sync=standard` in the guide may be sufficient now, as a result of the research and discussion in https://github.com/openzfs/zfs/issues/7734.  This is what I was currently planning on trying in this current system.

**Comment by rlaager** [comment]
Can you elaborate on how you determined that zpool_checkpoint was the problem? Later in the same comment you mentioned a problem between BIOS booting and GPT, which is completely different from checkpointing.

The docs specifically note that I tested zpool_checkpoint. I vaguely recall taking a checkpoint of the boot pool and making sure it could still boot.

**Comment by Shellcat-Zero** [comment]
When UEFI boot failed, I then tried BIOS booting, which also failed and additionally gave me partition table error messages (GPT apparently always shows error messages in legacy boot).  I then proceeded to try the install process as described in 18.04 (using 20.04) to see if there was some difference between the 18.04 process and 20.04, and so when seeing that there was a difference in the `bpool` features, I tried an install just using the features described for 18.04 which succeeded. When BIOS boot succeeded, I tried UEFI which also succeeded.  The `bpool` features are the only aspect I took from the 18.04 process for my 20.04 install.  If that had failed, I would have proceeded with the rest of the 18.04 process to see if it worked for 20.04.

**Comment by Shellcat-Zero** [comment]
One more hint was the 'unknown filesystem' errors shown in the grub prompt above, I had no way of booting the system from grub prompt with `zpool_checkpoint`.

**Comment by Shellcat-Zero** [comment]
Correction: It was the `error: compression algorithm` messages in the grub prompt that seemed suspicious.

**Comment by rlaager** [comment]
The `error: compression algorithm` thing is probably unrelated. I don't know why that occurs, but that occurs even with a `version=28` pool (i.e. no features).

I'm still a little skeptical that `zpool_checkpoint` is the problem. First off, you presumably didn't create a checkpoint. Second, this works fine for me. I just retested it now. It works with the checkpoint feature enabled (i.e. no checkpoint) and with it active (i.e. having a checkpoint). But, given that nothing in the HOWTO or zsys uses checkpoints, Ubuntu doesn't enable them in the installer, and your report of a problem, I've just removed it from the HOWTO out of an abundance of caution.

**Comment by chrcoluk** [comment]
I have confirmed this, I successfully followed the zfs root on ubuntu guide which omits the flag, I later decided to setup on debian using the debian guide, and I get the grub prompt.

I then redid the debian guide without the flag and it booted fine.

**Comment by lae** [comment]
Similarly to above, I followed the Debian guide (but with a few changes because I'm using Bullseye) and dropping to a GRUB prompt.

GRUB was complaining about `incorrect dnode type` when I attempted to list files on it from the GRUB command line. Leaving the `zpool_checkpoint` feature disabled also leaves the `large_dnode` feature disabled, so I think that probably explains why this turns out to be an issue. I tried backing up /boot, recreating it, and then copying everything back and running `grub-install` again but was still dropping into a prompt, but could at least list files in `bpool/BOOT/debian` (albeit some warnings? about compression algorithm not being supported).

I'm not seeing the reasoning behind using ZFS for /boot as well though, so I'm just going to do without.

**Comment by rlaager** [comment]
@lae zpool_checkpoint does not require large_dnode.
```
root@bullseye-bios-single-encryption:~# zpool get all bpool | grep feature@ | grep checkpoint
bpool  feature@zpool_checkpoint       enabled                        local
root@bullseye-bios-single-encryption:~# zpool get all bpool | grep feature@ | grep dnode
bpool  feature@large_dnode            disabled                       local
```
