### ISSUE TITLE
Proposed items to add to "Debian Buster Root on ZFS" guide

### ISSUE THREAD

**Issue by tehnic-take3** [openzfs/openzfs-docs#59]
Hello,
here some proposals for adding to this great guide to cover more common system usages:

If you use mysql/mariadb:
zfs create rpool/var/lib/mysql

If you use posgresql:
zfs create rpool/var/lib/postgresql

If you use virtualization (virt-manager, libvirt, ...):
zfs create -o canmount=off rpool/var/lib/libvirt
zfs create rpool/var/lib/libvirt/images

Install package console-setup in chroot environment (for keyboard layout configuration).
apt install console-setup

Best regards, Robert

**Comment by rlaager** [comment]
I deliberately removed the optional datasets for things like MySQL. There are a few reasons: 1) There are a lot of different things people might run, and I don't want a huge list. 2) I am trying to match the installer behavior. 3) For databases specifically, I do not want to be responsible for researching and explaining things like the best `recordsize` for each database.

Regarding console-setup, can you expand on what you changed? You mention keyboard configuration, but that actually seems like it should be keyboard-configuration, not console-setup:
```
     apt install --yes keyboard-configuration
     dpkg-reconfigure keyboard-configuration
```
or maybe both:
```
     apt install --yes keyboard-configuration console-setup
     dpkg-reconfigure keyboard-configuration console-setup
```

**Comment by tehnic-take3** [comment]
Hello,

keyboard-configuration is a dependency of console-setup, so installing console-setup is enough.
Installing console-setup is more like regular installation.

Additionally the needed command "setupcon" used in /usr/share/initramfs-tools/hooks/keymap is part of the package console-setup. From /usr/share/initramfs-tools/conf-hooks.d/zfs:

`# Setup the keyboard mapping so passphrases can be entered correctly.`
`KEYMAP=y`

This is important because especially the location of special chars usually included in good passphrases differ in different keyboard layouts (us, gb, de, ...).

So the following should work:

`apt install --yes console-setup`
`dpkg-reconfigure keyboard-configuration console-setup`

I personally prefer to use apt without "--yes", the needed dpkg-reconfigure's are called then automatically.

I suggest this to be added at the "localization" place/phase, where tzdata and locales are configured.

Best regards, Robert

**Comment by rlaager** [comment]
I have hopefully fixed this. If not, or you have other feedback, please let me know.
