### ISSUE TITLE
Question: grub install for mirror setup (ubuntu)

### ISSUE THREAD

**Issue by ddnexus** [openzfs/openzfs-docs#66]
This is not an issue, just a question about a step in the doc that I cannot google nor figure out why is needed, so your help would be very appreciated. Thank you!

From the doc: 
For UEFI booting, install GRUB to the ESP:
```
grub-install --target=x86_64-efi --efi-directory=/boot/efi \
    --bootloader-id=ubuntu --recheck --no-floppy
```
For a mirror or raidz topology, run this for the additional disk(s), incrementing the “2” to “3” and so on for both /boot/efi2 and ubuntu-2:

```
cp -a /boot/efi/EFI /boot/efi2
grub-install --target=x86_64-efi --efi-directory=/boot/efi2 \
    --bootloader-id=ubuntu-2 --recheck --no-floppy
```

Why the `cp -a /boot/efi/EFI /boot/efi2` ? 
I see that `grub-install` in the new efi-directories installs all the files, and the `/boot/efi2/EFI/ubuntu2/grub.cfg` is correctly identical in all the installations pointing to the right grub path. However without the `cp` grub would start in console mode.

Why?

Thank you

**Comment by rlaager** [comment]
`/boot/efi2` is on the second disk per step 4.7, "For a mirror or raidz topology, repeat these steps for the additional disks, using `/boot/efi2`, `/boot/efi3`, etc." You obviously need a copy of GRUB on the second disk if you want to boot off that when the first disk has failed.

I need to research the new support in Ubuntu for multiple EFI disks. That may change this slightly in terms of details, but the principle has to be the same: you must have a copy of GRUB on more than one disk.
