### ISSUE TITLE
zfs and zfs-testing repos for Fedora 33

### ISSUE THREAD

**Issue by gogi983** [openzfs/openzfs-docs#68]
Hi everyone,

Can you please add zfs and zfs-testing repos in zfs-release for Fedora release version 33, as it is out now and shipped with kernel 5.8, which is compatible with the last versions od zfs-on-linux, but I'm convinced I and other users wouldn't want a breakdown when upgrading to Fedora 33.

Thanks a lot.

**Comment by gmelikov** [comment]
Duplicate of https://github.com/openzfs/zfs/issues/11119 , please track that one.
