### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Dmole** [openzfs/openzfs-docs#70]
https://openzfs.github.io/openzfs-docs/man/8/zpoolconcepts.8.html
links to
https://github.com/openzfs/openzfs-docs/blob/master/docs/man/8/zpoolconcepts.8.rst
which is 404

Please fix that link and/or let me know the correct URL to edit that page from.

**Comment by Dmole** [comment]
Found it here;
https://github.com/openzfs/zfs/blob/master/man/man8/zpoolconcepts.8

**Comment by gmelikov** [comment]
You're right, html for man pages is generated from main repo, issue about wrong `contribute` https://github.com/openzfs/openzfs-docs/issues/2
