### ISSUE TITLE
Raspberry Pi How-To Typo

### ISSUE THREAD

**Issue by donniep** [openzfs/openzfs-docs#71]
@rlaager, I have the following issue with the Ubuntu 20.04 Root on ZFS for Raspberry Pi HOWTO:  Please note the typo in Step 1 #1 - the xd -d should be xz -d:

`curl -O https://cdimage.ubuntu.com/releases/20.04.1/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz
xd -d ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz`

Thanks for this how-to!  It worked great after I stopped trying to second-guess it.

**Comment by rlaager** [comment]
Thanks for the report!
