### ISSUE TITLE
Ubuntu 20.04 installation issue from guide

### ISSUE THREAD

**Issue by cardoe** [openzfs/openzfs-docs#92]
I know a GitHub issue isn't the right place but I'm hoping that this issue will spur adding some more "if this happens, do this" cases to the documentation. I recently followed the 20.04 install guide and rather than doing a debootstrap, I rsync'd over an existing system. At the `reboot` at step 6.4 I was prompted with:

<img width="801" alt="zfs-boot-failure" src="https://user-images.githubusercontent.com/8839/102220634-b65d6780-3ea6-11eb-8469-a0cb094971ad.png">

Ultimately I fixed this with the following:
```
zpool import -R /root -N 1622245071594617821
zpool import -N 9080151117160437766
zfs mount rpool/ROOT/ubuntu_cgk50j
zfs mount bpool/BOOT/ubuntu_cgk50j
zfs mount -a
exit
```

For a split second I see `/ROOT/ubuntu/cgk50j: No such file or directory` after the exit and then the system boots normally.

This unfortunately happens every time I boot and my `/etc/zfs/zfs-list.cache/*` files have a `/root` prefix that needs to be stripped before I reboot. I've tried to nuke `/etc/zfs/zpool.cache` (idea from openzfs/zfs#3918) but that doesn't seem to cure it.

**Comment by rlaager** [comment]
Some random thoughts:

- Did you rebuild your initrd after deleting the cache file?
- Try getting some debug logs from the initramfs: https://wiki.debian.org/InitramfsDebug#Saving_debug_information
- I see you are importing the pools by ID. I've never done that. Are you unable to import them using "rpool" and "bpool"? Have you tried `zpool import ... ID rpool` (and likewise for bpool) to try setting the names on import?

**Comment by cardoe** [comment]
Thanks for the reply @rlaager. I've been digging into this a bit further as well and think I've figured it out. The issue is that I'm actually booting a Xen dom0 (I know not recommended). I believe the issue is related to the GRUB generation for Xen. Ubuntu currently patches their GRUB to skip `/etc/grub.d/10_linux` because it relies on `grub-probe` against the rpool. However your documentation notes that the reason for the bpool / rpool split that GRUB doesn't support the features of the rpool so it makes sense that `grub-probe` doesn't work.

Upstream GRUB has the following:
https://git.savannah.gnu.org/cgit/grub.git/tree/util/grub.d/10_linux.in#n74
https://git.savannah.gnu.org/cgit/grub.git/tree/util/grub.d/20_linux_xen.in#n82

But Ubuntu has patch it in the following https://git.launchpad.net/ubuntu/+source/grub2/tree/util/grub.d/10_linux.in?h=applied/ubuntu/focal-updates#n133 which disables 10_linux for ZFS in favor of their custom https://git.launchpad.net/ubuntu/+source/grub2/tree/util/grub.d/10_linux_zfs.in?h=applied/ubuntu/focal-updates

It appears I'm not the only person running into this:
- https://askubuntu.com/questions/1271948/ubuntu-20-04-with-zfs-root-fails-to-boot-after-installing-xen
- http://savannah.gnu.org/bugs/?59614
- https://savannah.gnu.org/bugs/index.php?58555

So the fix is going to be to do the same rpool lookup style that 10_linux_zfs does but in 20_linux_xen. If it's okay with you I'd like to use this issue as the central documenting place for this issue for folks until I can get the appropriate patches merged in.

**Comment by cardoe** [comment]
> Some random thoughts:

I realized I didn't answer your questions.

> 
>     * Did you rebuild your initrd after deleting the cache file?

So I tried this and when I figured out the GRUB config issue and set the ZFS= correctly I did this before rebooting.

> 
>     * Try getting some debug logs from the initramfs: https://wiki.debian.org/InitramfsDebug#Saving_debug_information

This is what caused me to notice the GRUB setup being wrong so thank you.

> 
>     * I see you are importing the pools by ID. I've never done that. Are you unable to import them using "rpool" and "bpool"? Have you tried `zpool import ... ID rpool` (and likewise for bpool) to try setting the names on import?

Importing them with rpool and bpool worked. It just never occurred to me to try this. I saw the ID and assumed that's how I needed to do it.

**Comment by rlaager** [comment]
Yeah, based on your analysis, it sounds like you'll need to do some GRUB script integration work if you want zsys and Xen to work together.

Another option would be to forgo zsys, such that you just have an `rpool/ROOT/ubuntu` (rather than `rpool/ROOT/ubuntu_ID`) dataset. Then in `/etc/default/grub`, set `GRUB_CMDLINE_LINUX="root=ZFS=rpool/ROOT/ubuntu"`

Or put differently, you might want to try this:

1. Set `GRUB_CMDLINE_LINUX="root=ZFS=rpool/ROOT/ubuntu_cgk50j"` in `/etc/default/grub` (and run `update-grub`).
2. Remove the zsys package. Make sure that doesn't remove the zfs-initramfs package. (Make sure you are okay with the risk of needing to boot into a Live CD to recover this.)
3. Optionally, consider renaming to just `rpool/ROOT/ubuntu`. I'm not sure if this would require a Live CD. Definitely make sure to update the zed cache, the initramfs, and GRUB before rebooting.

**Comment by cardoe** [comment]
I agree that zsys and a Ubuntu Xen system will need some love to really work nicely. I was just hoping that the basics of booting from a ZFS root pool would work which they didn't. The `ROOT/ubuntu_id` part appears to be working fine. It's the identification of `rpool` that's flawed. I came up with two ways that appear to work. I feel like the best approach would be to replace the need for `grub-probe`, which is the part that's not working. 

Replace:
```
	rpool=`${grub_probe} --device ${GRUB_DEVICE} --target=fs_label 2>/dev/null || true`
```
With:
```
	rpool=`${grub_probe} --device ${GRUB_DEVICE} --target=fs_label 2>/dev/null || zdb -l ${GRUB_DEVICE} | awk -F \' '/ name/ { print $2 }'`
```

**Comment by cardoe** [comment]
https://lists.gnu.org/archive/html/grub-devel/2020-12/msg00239.html is what I proposed with this change.
