### ISSUE TITLE
unsupported features in default install

### ISSUE THREAD

**Issue by gYxjuTyK** [openzfs/openzfs-docs#94]
@rlaager, I have the following issue with the Debian Buster Root on ZFS HOWTO:

This didn't work straight from the instructions, it made an unbootable system: 

cannot import 'rpool': unsupported version or feature
This pool uses the following feature(s) not supported by this system:
com.datto:encryption
org.zfsonlinux:project_quota
com.delphix:spacemap_v2

Ended up having to redo everything including the bootpool with
zpool create - .... feature@...=disabled .....

I think this needs a warning/note in the guide

**Comment by rlaager** [comment]
I've definitely tested the Buster guide with encryption (I still have the VM), so obviously the encryption feature exists. Did you forget to enable backports or something? What version of ZFS do you have installed (`dpkg --status zfsutils-linux`)?

**Comment by gYxjuTyK** [comment]
You're right, I might have forgot that backports.
# libzfs2linux  zfs-dkms  zfs-initramfs  zfs-zed  zfsutils-linux     0.7.12-2+deb10u2
# apt -s install -t buster-backports zfs-initramfs
...
The following packages will be upgraded:
  libnvpair1linux libuutil1linux libzfs2linux libzpool2linux spl-dkms zfs-dkms zfs-initramfs zfsutils-linux
Inst zfs-initramfs [0.7.12-2+deb10u2] (0.8.6-1~bpo10+1 Debian Backports:buster-backports [all]) []
...
I used the debian-live-10.7.0-amd64 iso.

# zpool create -o ashift=12 -o feature@encryption=disabled -o feature@project_quota=disabled -o feature@spacemap_v2=disabled  -o feature@async_destroy=enabled -o feature@bookmarks=enabled -o feature@embedded_data=enabled -o feature@empty_bpobj=enabled -o feature@enabled_txg=enabled -o feature@extensible_dataset=enabled -o feature@filesystem_limits=enabled -o feature@hole_birth=enabled -o feature@large_blocks=enabled -o feature@lz4_compress=enabled -o feature@spacemap_histogram=enabled -o feature@userobj_accounting=enabled -o feature@zpool_checkpoint=enabled -o feature@resilver_defer=enabled -O acltype=posixacl -O canmount=off -O compression=lz4 -O devices=off -O normalization=formD -O relatime=on -O xattr=sa -O mountpoint=/ -R /mnt bpool mirror /dev/disk/by-id/ata-DISK1-part3 /dev/disk/by-id/ata-DISK2-part3

# zpool create -o ashift=12 -o feature@encryption=disabled -o feature@project_quota=disabled -o feature@spacemap_v2=disabled -O acltype=posixacl -O canmount=off -O compression=lz4 -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa -O mountpoint=/ -R /mnt rpool mirror /dev/disk/by-id/ata-DISK1-part4 /dev/disk/by-id/ata-DISK2-part4


But in..
Step 4: System Configuration
6. Install ZFS in the chroot env
..it is not using -t backports ?

**Comment by rlaager** [comment]
Right, the installed environment uses the 90_zfs preferences file to choose the backports version. It sounds like you've maybe gotten to the bottom of this? I'm going to close this. If you have any further questions, just leave a comment and I'll reopen it.
