### ISSUE TITLE
Missing step to populate /boot/efi on mirrored disks in Ubuntu 20.04 guide?

### ISSUE THREAD

**Issue by deviantintegral** [openzfs/openzfs-docs#95]
I'm setting up a 2-way mirror. At `Step 6: First Boot`, `Install GRUB to additional disks:`, there's a line to run `dpkg-reconfigure grub-efi-amd64` to populate `/boot/efi` on all drives. When I run it, I'm not given an option to select multiple partitions, only showing screens for grub options.

I only have a single line in for `/dev/vda1` in `/etc/fstab`, so it's not clear to me how grub would know there's multiple partitions to use. Do I need to manually copy the EFI files to the partition as mentioned in the boot errata? I'm happy to file a PR against the docs, but I'm not sure what exactly, if anything needs to be changed.

**Comment by rlaager** [comment]
To be clear, did you try to run `dpkg-reconfigure grub-efi-amd64` before or after rebooting (i.e. booted from Live CD or installed system)?

When I tested it, it did not prompt in the chroot, but did after I rebooted. I have no idea why, but maybe that's related (even if you are running it in the normal system, maybe it's the same underlying cause).

**Comment by deviantintegral** [comment]
This is after rebooting off of the installed system.

**Comment by rlaager** [comment]
Run this: `DEBCONF_DEBUG=developer dpkg-reconfigure grub-efi-amd64` and send me the output somehow (here, pastebin, email to rlaager@wiktel.com, etc.). Specifically, I'm wondering what is different before the bit about grub-efi/install_devices (or indeed, if that even shows up).

**Comment by rlaager** [comment]
Also, make sure you have a `/boot/grub/x86_64-efi/core.efi` file. That seems necessary (i.e. so this code would be run):
```
case grub-efi-amd64 in
  grub-efi-ia32)  target=i386-efi ;;
  grub-efi-amd64) target=x86_64-efi ;;
  grub-efi-ia64)  target=ia64-efi ;;
  grub-efi-arm)   target=arm-efi ;;
  grub-efi-arm64) target=arm64-efi ;;
esac
# Check /boot/grub to see if we previously installed to an ESP. We don't
# want to trigger the install code just by installing the package,
# normally the installer installs grub itself first.
if test -e /boot/grub/$target/core.efi; then
  db_get grub2/no_efi_extra_removable
  if [ "$RET" = true ]; then
    NO_EXTRA_REMOVABLE="--no-extra-removable"
  fi
  NO_NVRAM="$(no_nvram_arg)"
  run_grub_multi_install --target="$target" "$NO_EXTRA_REMOVABLE" "$NO_NVRAM"
fi
```

**Comment by deviantintegral** [comment]
The `/boot/grub/x86_64-efi/core.efi` file exists for me.

Here's the debug output: https://gist.github.com/deviantintegral/1b9b17358723a38302f5d1aa9b398ae2

This might explain why the question isn't being asked?

```
debconf (developer): <-- INPUT low grub2/force_efi_extra_removable
debconf (developer): --> 10 "grub2/force_efi_extra_removable" doesn't exist
```

```
debconf (developer): <-- INPUT high grub-efi/install_devices
debconf (developer): --> 30 question skipped
```

**Comment by deviantintegral** [comment]
I discovered the source of this. Somehow, I had a `/boot/grub/grubenv` file on my root pool. I did mask the `grub-initrd-fallback.service` as instructed at step 7, so I wonder if somehow that file was created before that step?

Once I removed it, I could mount `/boot/grub`, and running dpkg-reconfigure allowed me to install GRUB on both disks.

**Comment by rlaager** [comment]
Weird. I'll have to keep an eye open for that. But I don't have any immediate idea of how that could have happened.

I'm not sure what action I could take next. I'm going to close this since it's working for you. If you get any more information, feel free to put it here. I can always reopen. If there's something I can do to improve the instructions, I definitely want to.
