### ISSUE TITLE
Debian: Should /boot/efi be mounted during boot?

### ISSUE THREAD

**Issue by foo-git** [openzfs/openzfs-docs#99]
In the last days I migrated my server successfully on ZFS, root and all. Thanks for the really helpful documentation of this tedious process!

System is running latest Debian Testing.

I stumbled upon an issue, that the /boot/efi partition is not mounted during boot, and I see the following error messages:
```
Dez 30 12:23:13 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start timed out.
Dez 30 12:23:13 cloudfoo systemd[1]: Timed out waiting for device /dev/disk/by-uuid/E032-A5C1.
Dez 30 12:23:13 cloudfoo systemd[1]: Dependency failed for File System Check on /dev/disk/by-uuid/E032-A5C1.
Dez 30 12:23:13 cloudfoo systemd[1]: Dependency failed for /boot/efi.
Dez 30 12:23:13 cloudfoo systemd[1]: boot-efi.mount: Job boot-efi.mount/start failed with result 'dependency'.
Dez 30 12:23:13 cloudfoo systemd[1]: systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service: Job systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service/start failed with result 'dependency'.
Dez 30 12:23:13 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start failed with result 'timeout'.

```
I assume (for whatever reason) that it's too early to mount the EFI partition. As a workaround I added `x-systemd.requires=zfs-import-bpool.service` into fstab and increasing the timeout to 2 seconds resulting in the following line:
```
/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat nofail,x-systemd.device-timeout=2,x-systemd.requires=zfs-import-bpool.service 0 1
```
On the next boot the error message disappeared, and /boot/efi was successfully mounted.

I'm not entirely sure that this workaround is the right way to handle it, maybe someone else has any thoughts?

[Upon further reading](https://bugzilla.redhat.com/show_bug.cgi?id=1077984), it seems that persistently mounting /boot/efi is not such a great idea due to potential filesystem corruption. There the recommended solution is:
```
/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat x-systemd.idle-timeout=1min,x-systemd.automount,noauto 0 1
```

**Comment by rlaager** [comment]
Thanks for the information.

I recently changed this in the instructions, based on the behavior of the Ubuntu installer. Since this seems to be reproducible for you, can you test:
```
UUID=E032-A5C1 /boot/efi vfat nofail,x-systemd.device-timeout=1 0 1
```
That is, use `UUID=` instead of `/dev/disk/by-uuid/`?

Also, regardless of whether that one works or not, can you confirm that this (from your comment) works:
```
/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat x-systemd.idle-timeout=1min,x-systemd.automount,noauto 0 1
``` 
You listed it, but it's not clear from your comment if you actually tried it, and I'd like to be sure before I make changes. Specifically, for this second test, "works" means both that A) the system comes up without error, and B) that if you try to access `/boot/efi` (e.g. with `ls`) that it is correctly automounted and you see its contents.

**Comment by foo-git** [comment]
I can confirm that 2) works, i.e. `/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat x-systemd.idle-timeout=1min,x-systemd.automount,noauto 0 1`, as this is the configuration I'm running right now. I can confirm that the system boots correctly, that no error message appears, and that `/boot/efi` gets dynamically mounted/unmounted upon access:

```
Jan 01 15:39:42 cloudfoo systemd[1]: Reached target ZFS pool import target.
Jan 01 15:39:42 cloudfoo systemd[1]: Mounting /boot...
Jan 01 15:39:42 cloudfoo systemd[1]: Starting Wait for ZFS Volume (zvol) links in /dev...
Jan 01 15:39:43 cloudfoo systemd[1]: Mounted /boot.
Jan 01 15:39:43 cloudfoo zvol_wait[2665]: No zvols found, nothing to do.
Jan 01 15:39:44 cloudfoo systemd[1]: Set up automount boot-efi.automount.
[...]
Jan 05 08:32:14 cloudfoo systemd[1]: boot-efi.automount: Got automount request for /boot/efi, triggered by 2888090 (ls)
Jan 05 08:32:14 cloudfoo systemd[1]: Created slice system-systemd\x2dfsck.slice.
Jan 05 08:32:14 cloudfoo systemd[1]: Listening on fsck to fsckd communication Socket.
Jan 05 08:32:14 cloudfoo systemd[1]: Starting File System Check on /dev/disk/by-uuid/E032-A5C1...
Jan 05 08:32:14 cloudfoo systemd[1]: Started File System Check Daemon to report status.
Jan 05 08:32:15 cloudfoo systemd-fsck[2888095]: fsck.fat 4.1 (2017-01-24)
Jan 05 08:32:15 cloudfoo systemd-fsck[2888095]: /dev/sde2: 9 files, 10658/2064856 clusters
Jan 05 08:32:15 cloudfoo systemd[1]: Finished File System Check on /dev/disk/by-uuid/E032-A5C1.
Jan 05 08:32:15 cloudfoo systemd[1]: Mounting /boot/efi...
Jan 05 08:32:15 cloudfoo systemd[1]: Mounted /boot/efi.
[...]
Jan 05 08:33:36 cloudfoo systemd[1]: Unmounting /boot/efi...
Jan 05 08:33:36 cloudfoo systemd[2887858]: boot-efi.mount: Succeeded.
Jan 05 08:33:36 cloudfoo systemd[1]: boot-efi.mount: Succeeded.
Jan 05 08:33:36 cloudfoo systemd[1]: Unmounted /boot/efi.
```

Regarding 1), I'm not sure if specifying `UUID=` instead of `/dev/disk/by-uuid/` will help anything, but I will test it 😁

**Comment by foo-git** [comment]
So I just tested 1), and the behaviour of using `UUID=` is the same as to using `/dev/disk/by-uuid/`, i.e. error messages and no mount on boot:
```
Jan 05 13:16:02 cloudfoo systemd[1]: Starting Rule-based Manager for Device Events and Files...
Jan 05 13:16:02 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start timed out.
Jan 05 13:16:02 cloudfoo systemd[1]: Timed out waiting for device /dev/disk/by-uuid/E032-A5C1.
Jan 05 13:16:02 cloudfoo systemd[1]: Dependency failed for File System Check on /dev/disk/by-uuid/E032-A5C1.
Jan 05 13:16:02 cloudfoo systemd[1]: Dependency failed for /boot/efi.
Jan 05 13:16:02 cloudfoo systemd[1]: boot-efi.mount: Job boot-efi.mount/start failed with result 'dependency'.
Jan 05 13:16:02 cloudfoo systemd[1]: systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service: Job systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service/start failed with result 'dependency'.
Jan 05 13:16:02 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start failed with result 'timeout'.
Jan 05 13:16:03 cloudfoo systemd[1]: Finished zfs-import-bpool.service.
[...]
Jan 05 13:16:07 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start timed out.
Jan 05 13:16:07 cloudfoo systemd[1]: Timed out waiting for device /dev/disk/by-uuid/E032-A5C1.
Jan 05 13:16:07 cloudfoo systemd[1]: Dependency failed for File System Check on /dev/disk/by-uuid/E032-A5C1.
Jan 05 13:16:07 cloudfoo systemd[1]: Dependency failed for /boot/efi.
Jan 05 13:16:07 cloudfoo systemd[1]: boot-efi.mount: Job boot-efi.mount/start failed with result 'dependency'.
Jan 05 13:16:07 cloudfoo systemd[1]: systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service: Job systemd-fsck@dev-disk-by\x2duuid-E032\x2dA5C1.service/start failed with result 'dependency'.
Jan 05 13:16:07 cloudfoo systemd[1]: dev-disk-by\x2duuid-E032\x2dA5C1.device: Job dev-disk-by\x2duuid-E032\x2dA5C1.device/start failed with result 'timeout'.
```
Checking `/boot/efi` yields:
```
root@cloudfoo:/boot/efi# ls -al
drwxr-xr-x 2 root root 2 28. Dez 14:30 .
drwxr-xr-x 4 root root 8  5. Jan 12:59 ..
```

**Comment by rlaager** [comment]
Thanks for your research on this! You can see the approach I took, and my rationale, in the linked commit (c00aa93389260573349303e95cb3e6e3cb805b09).

I would be curious if `/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat defaults 0 0` works for you. If not, that could change my mind (or suggest further troubleshooting is necessary).

**Comment by foo-git** [comment]
Thanks for your explanations.
I just tested the change you proposed, i.e. `/dev/disk/by-uuid/E032-A5C1 /boot/efi vfat defaults 0 0`, and my system booted without any error messages. `/boot/efi` is automatically mounted and accessible.

While I feel somewhat more comfortable using the automount-approach, I can understand that you want to keep it closer to the Ubuntu installer. Thanks for offering it as an alternative  👍
